### ISSUE TITLE
Water Doesn't Render Through Glass

### ISSUE THREAD

**Issue by xavierplayr** [Madis0/fabulously-optimized#100]
![2021-07-25_12 40 27](https://user-images.githubusercontent.com/49925696/126906758-a28dc969-af73-4f6f-815a-f13e1c0a2e0d.png)

**Comment by Madis0** [comment]
You created the wrong type of issue, either way see this bug: https://github.com/CaffeineMC/sodium-fabric/issues/38

**Comment by Rajbir98** [comment]
fixed it sodium 0.3.2
