### ISSUE TITLE
After Putting Iris Within Mod Folder Game Crashes Upon Load

### ISSUE THREAD

**Issue by Lexutive** [Madis0/fabulously-optimized#105]
### Describe the bug

After installing Iris into the mod folder I get an error (followed by Minecraft crashing) after the red loading screen has completed.

[crash-2021-08-02_11.52.26-client.txt](https://github.com/Madis0/fabulously-optimized/files/6919058/crash-2021-08-02_11.52.26-client.txt)

### Expected behavior

I expected to have the ability to use shaders.

### Observed/actual behavior

I saw nothing because the game crashed upon loading.

### Steps To Reproduce

1. Install Iris
2. Put into mods folder
3. Open Minecraft
4.

### Modpack version

1.16.5

### Launcher

Curseforge Launcher

### Install method

Upgraded an existing profile (please write below, what version to what version)

**Comment by Madis0** [comment]
If you want to use Iris in 1.16.5, please remove Sodium (Iris includes a compatible one). Otherwise try out the 1.17 or 1.17.1 versions that already include Iris.

**Comment by Lexutive** [comment]
Alright, thanks!
