### ISSUE TITLE
BetterBeds & FastChest not removed in 2.1.0-beta.3

### ISSUE THREAD

**Issue by nchristopher** [Madis0/fabulously-optimized#107]
### Describe the bug

In the changelog for `2.1.0-beta.3`, BetterBeds & FastChests were supposedly removed. However, they're both still present in the Packwiz config.

From what I can tell, this doesn't cause any issues, but should still be addressed. This issue is similar to #97.

### Expected behavior

BetterBeds & FastChest were both removed.

### Observed/actual behavior

BetterBeds & FastChest are still present.

### Steps To Reproduce

Install `2.1.0-beta.3`

### Modpack version

2.1.0-beta.3

### Launcher

MultiMC

### Install method

Fresh install/new profile

**Comment by Madis0** [comment]
Thank you. I guess I should clear up the packwiz mods folder every time before adding new ones 😄
