### ISSUE TITLE
Indium

### ISSUE THREAD

**Issue by Madis0** [Madis0/fabulously-optimized#11]
**Mod name**
Indium

**Curseforge link**
https://www.curseforge.com/minecraft/mc-mods/indium

**Modrinth link**
https://modrinth.com/mod/indium

**Other link**
https://github.com/comp500/Indium

**What it does**
Adds rendering API to Sodium

**Why should it be in the modpack**
To add better grass and CTM support

**Why shouldn't it be in the modpack**
Incompatible with the released version of Sodium

**Categories**

- [ ] Performance optimization
- [ ] Graphics optimization
- [ ] New feature
- [ ] Optifine parity
- [x] Fixes a bug/dependency

**Additional details**

Edit: [an experimental version of Sodium](https://www.curseforge.com/minecraft/mc-mods/sodium-next) is now on CF, but I will wait for an official/Iris one  
Edit 2: now released on Modrinth

**Comment by Alejandro-Sosa** [comment]
Latest sodium build has this fixed ^^

**Comment by Madis0** [comment]
@Alejandro-Sosa Wow, that's great news! It probably takes time before it is released on CF though...

**Comment by Alejandro-Sosa** [comment]
True, isn't it possible to include versions straight from github?

**Comment by Madis0** [comment]
Unfortunately not in CF itself, as they don't really like forks/unofficial JARs if the mod is already published there.

**Comment by Madis0** [comment]
Thanks. Seems like now it's just waiting for Sodium to properly update and support it (CF doesn't allow forks of an already-published mod).

**Comment by MulverineX** [comment]
I've done testing with 1.16 & 1.17 with & without Iris, it all works. (w/ ConnectedBlockTextures & LambdBetterGrass)

> I'm waiting for Sodium 0.2.0 to release [Indium] on curseforge, jelly is having issues with her curseforge account currently
@comp500

**Comment by MulverineX** [comment]
Here's the MultiMC instances for the above results

[Indium 1.17 Testing.zip](https://github.com/Madis0/fabulously-optimized/files/6750984/Indium.1.17.Testing.zip)
[Indium 1.16 Testing.zip](https://github.com/Madis0/fabulously-optimized/files/6750989/Indium.1.16.Testing.zip)

**Comment by Madis0** [comment]
I appreciate the testing but yes, I'll wait out. No 1.16 release is planned, I don't do backports.

**Comment by Rajbir98** [comment]
But to add Lamda BetterGrass Indium Is Important You can See it in LamdaBettergrass CF Comments

**Comment by MulverineX** [comment]
@Rajbir98 yes we are aware, LambdaBetterGrass will get added when Indium is added. it's dependant.

**Comment by MulverineX** [comment]
Sodium 1.17 & Indium are now officially released!

https://modrinth.com/mod/sodium/version/1b0GhKHj

https://modrinth.com/mod/indium/version/uTvfCUBM

Just need to get these reviewed and added to the CF modpack 3rd party site list

**Comment by Madis0** [comment]
@MulverineX I am already aware - that Sodium is available on 2.1.0-beta.1 and Indium is on my to-do 😄

**Comment by Madis0** [comment]
In my initial testing with Indium and a bunch of Rendering API mods that are tracked here, the performance was bad and there were several graphics glitches :(
Seems resolvable by testing mods one by one and reporting bugs, but it means I won't release Indium mods as soon as I expected.

**Comment by MulverineX** [comment]
CBT & LBG worked perfectly though, I don't see what the problem is. FO doesn't have to be compatible with external mods

**Comment by Madis0** [comment]
I tried LBG, CEM and EME and something was very off. Will try again soon.

**Comment by MulverineX** [comment]
"edit: when Sodium updates" What does that have to do with anything? Is there some context from Fabricord that's missing?

**Comment by Madis0** [comment]
Context is that people are experiencing glitches, memory leaks and other bugs. I want to get things smooth and stable before moving on.

**Comment by Madis0** [comment]
I've decided to do a public beta to get feedback on different people's hardware, please compare 2.1.0-beta.2 and 2.1.0-beta.3 and vote on the poll listed in the changelog.
