### ISSUE TITLE
Game Lags When Near Ocean

### ISSUE THREAD

**Issue by Rajbir98** [Madis0/fabulously-optimized#111]
### Describe the bug

I was playing in my creative world i went to a beach it started lagging then i went to plains biome lag stops
can u look for a mod to fix this

### Expected behavior

no fps change while near ocean

### Observed/actual behavior

fps loss when near ocean

### Steps To Reproduce

Go near a ocean u will not able to reproduce if your pc is not low end

### Modpack version

2.10 beta 4

### Launcher

Other (please write below)

### Install method

Other (please write below)

**Comment by Madis0** [comment]
Please try the latest version of Sodium (on Modrinth) and see if that helps. I will release a next version of the pack soon with it when Iris updates to include the new Sodium.

**Comment by Rajbir98** [comment]
yes I the latest sodium version fixes this so I may close this issue
