### ISSUE TITLE
CIT Resewn

### ISSUE THREAD

**Issue by Madis0** [Madis0/fabulously-optimized#112]
### Mod name

CIT Resewn

### Curseforge link

https://www.curseforge.com/minecraft/mc-mods/cit-resewn

### Other links

https://github.com/SHsuperCM/CITResewn/issues

### What it does

Adds support for Optifine's custom item textures

### Why should it be in the modpack

More Optifine parity, supports Sodium, alternative to #77 

### Why shouldn't it be in the modpack

"mod receives updates faster and more frequently through modrinth", some features unsupported
### Categories

Graphics optimization, Works like Optifine/Bedrock Edition/Forge/etc

### Additional details

Tested with https://www.curseforge.com/minecraft/texture-packs/justtimms-custom-additions

**Comment by srnyx** [comment]
@Madis0 What about Custom Entity Models (CEM)?

**Comment by Madis0** [comment]
CIT Resewn provides support for custom _items_ (things in the inventory), CEM provides support for custom _entities_ (mostly mobs).

**Comment by srnyx** [comment]
> CIT Resewn provides support for custom _items_ (things in the inventory), CEM provides support for custom _entities_ (mostly mobs).

Ohhhhhh, thank you!
