### ISSUE TITLE
Continuity

### ISSUE THREAD

**Issue by Madis0** [Madis0/fabulously-optimized#114]
### Mod name

Continuity, previously known as NTCM

### Curseforge link

https://www.curseforge.com/minecraft/mc-mods/continuity

### Other links

https://modrinth.com/mod/continuity
https://github.com/PepperCode1/Continuity

### What it does

Optifine's connected textures and other area-specific textures (e.g. specific biomes have different block design) 

### Why should it be in the modpack

Alternative to #5 

### Why shouldn't it be in the modpack

Not publicly released yet, need more info of what features, requirements etc it has

### Categories

Graphics optimization, Works like Optifine/Bedrock Edition/Forge/etc

### Additional details

Just waiting for CF approval now

**Comment by Rajbir98** [comment]
I have tested this mod it is a nice mod

**Comment by Rajbir98** [comment]
The latest Version of Mod Is Broken

**Comment by Madis0** [comment]
> The latest Version of Mod Is Broken

Can you elaborate? If you're referring to #140, I tried creating/installing a version without it as well with the same result.
