### ISSUE TITLE
Smooth Scrolling Everywhere

### ISSUE THREAD

**Issue by RozeFound** [Madis0/fabulously-optimized#116]
### Mod name

Smooth Scrolling Everywhere

### Curseforge link

https://www.curseforge.com/minecraft/mc-mods/smooth-scrolling-everywhere-fabric

### Other links

https://github.com/shedaniel/SmoothScrollingEverywhere

### What it does

Smooth Scrolling

### Why should it be in the modpack

Coz it was here by some reason.

### Why shouldn't it be in the modpack

idk

### Categories

Graphics optimization

### Additional details

Seems to be updated and release to CF soon. 
You can build it from source for now, as I do.
[SmoothScrollingEverywhere-3.0.3-unstable-mc1.17.1.zip](https://github.com/Madis0/fabulously-optimized/files/7121073/SmoothScrollingEverywhere-3.0.3-unstable-mc1.17.1.zip)

**Comment by fredster33** [comment]
LGTM.

**Comment by RozeFound** [comment]
Не понимаю правда зачем тебе нужен этот мод, не особо то и приятно с ним менюшки ощущаются.

**Comment by Rajbir98** [comment]
it here its now updated but unstable
https://www.curseforge.com/minecraft/mc-mods/smooth-scrolling-everywhere-fabric/download/3453127

**Comment by Madis0** [comment]
Thanks for letting me know!
The reason why this was included in the first place was to increase perception of smoothness. But now that I compare it with and without the mod, I think I will not add it back because it doesn't seem to improve the experience that much. Feel free to comment on this.

**Comment by fredster33** [comment]
Personally the main difference for me is that there is a fluid overscroll animation. I like having an overscroll animation as it is intuitive, and "flows better". I do admit that it is fairly minor, though.

**Comment by RozeFound** [comment]
@Madis0 sorry for off-topic, but Google translate? I've think you know Russian (And this is what your site say)

**Comment by Madis0** [comment]
@RozeFound Haha, good observation 😄 
Well, I could understand most of your sentence, but I used machine translation out of habit and to "fill in the gaps" (translate the words I forgot).

**Comment by Madis0** [comment]
Decided against this:
* Mod was updated very late and by a contributor, does not give confidence in future updates
* There are very few scrollable views overall where this is visible
* It does not necessarily increase the perception of speed
