### ISSUE TITLE
Crash on first launch

### ISSUE THREAD

**Issue by Madis0** [Madis0/fabulously-optimized#117]
### Describe the bug

The modpack may crash on the first launch after a fresh install. Does not seem to affect subsequent launches.

### Expected behavior

No crash

### Observed/actual behavior

Crashes before the loading screen (logs in issue below)

### Steps To Reproduce

1. Download FO 2.1.0
2. Launch
3. Get crash
4. Launch again
5. Works

### Modpack version

2.1.0

### Launcher

Curseforge Launcher

### Install method

Fresh install/new profile

### Additional context

https://github.com/kvverti/colormatic/issues/49

I am not yet sure how to mitigate it (other than removing the mod) and whether it is even necessary if the crash only appears once. Maybe bundling the config normally instead of using YOSBR might help.
Is there anyone here who gets more crashes than one?

Edit: found a workaround, should include `mixins.sodium.refmap.json`

**Comment by RozeFound** [comment]
I can confirm, me and my friends felt this bug too. But we used MultiMC.

**Comment by fredster33** [comment]
Doesn't crash for me.
