### ISSUE TITLE
Create a "blank" option for issue templates

### ISSUE THREAD

**Issue by fredster33** [Madis0/fabulously-optimized#118]
I'm having to pick between issue templates that don't actually fit for my case, because there's no simple "blank" option for the issue template. Instead, there should be a blank issue template option. More details at https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository .

I apologize for having to label this issue wrongly forcibly, but unfortunately I can't do it some other way. This issue should be tagged with "meta" instead.

**Comment by Madis0** [comment]
Agreed, it was disabled because someone ignored it, despite there being a valid option 😄

**Comment by fredster33** [comment]
Got it, I'll open issues that don't fit the issue templates with the "option" template in the future.

**Comment by Madis0** [comment]
No, I meant that was why it was disabled, now I enabled it because I need it as well 😄

**Comment by fredster33** [comment]
Ah, okay, got it :)
