### ISSUE TITLE
BisectHosting link redirects to main page

### ISSUE THREAD

**Issue by fredster33** [Madis0/fabulously-optimized#119]
The BisectHosting link listed throughout the README, CurseForge page and wiki pages just redirect to the BisectHosting main page.

I apologize for having to label this issue wrongly forcibly, but unfortunately I can't do it some other way. This issue should be tagged with "meta" instead. See also #118 .

**Comment by Madis0** [comment]
Thanks for the support!

I checked and the link is valid (so the redirect seems intentional), the click statistics reflect that as well.
