### ISSUE TITLE
ASH - Another Simple HUD

### ISSUE THREAD

**Issue by fredster33** [Madis0/fabulously-optimized#120]
### Mod name

ASH - Another Simple HUD

### Curseforge link

https://www.curseforge.com/minecraft/mc-mods/ash-another-simple-hud

### Other links

https://modrinth.com/mod/ash
https://github.com/umollu/ash

### What it does

Adds a FPS count, coordinate and compass HUD. (These are configurable, and defaults can probably be set.)

Personally, I think just including the coordinate is best. It adds Bedrock parity and is very "vanilla-like".

### Why should it be in the modpack

Adds coordinates to the HUD without having to press F3 and pick out the coordinates from a cluttered interface.

### Why shouldn't it be in the modpack

Coordinate text is displayed without a background, meaning that in completely white settings it may be hard to read.

### Categories

New feature, Works like Optifine/Bedrock Edition/Forge/etc

**Comment by Madis0** [comment]
Already available in Sodium Extra, see the video settings.

**Comment by fredster33** [comment]
Yes - just realized and was about to self-close
