### ISSUE TITLE
EditSign

### ISSUE THREAD

**Issue by fredster33** [Madis0/fabulously-optimized#121]
### Mod name

EditSign

### Curseforge link

https://www.curseforge.com/minecraft/mc-mods/edit-sign

### Other links

https://modrinth.com/mod/editsign
https://github.com/RakSrinaNa/EditSign

### What it does

Allows editing signs after placement by right clicking.

### Why should it be in the modpack

Makes it much less of a hassle to edit signs after placement, as without this mod you would need to memorize/screenshot the text, destroy the sign, and place the sign with the new text.

### Why shouldn't it be in the modpack

Doesn't work on servers, see https://github.com/RakSrinaNa/EditSign/issues/62

### Categories

New feature

**Comment by Madis0** [comment]
This will never work on servers, unless vanilla adds it and that breaks the consistency. I want to keep singleplayer-only mods to a minimum, possibly only performance improvements like Lithium.
