### ISSUE TITLE
Don't Clear Chat History

### ISSUE THREAD

**Issue by fredster33** [Madis0/fabulously-optimized#123]
### Mod name

Don't Clear Chat History

### Curseforge link

Edit by Madis0: https://www.curseforge.com/minecraft/mc-mods/dont-clear-chat-history

### Other links

https://modrinth.com/mod/sUbMm93i
https://github.com/wafflecoffee/DCCH

### What it does

Doesn't clear the messages you've sent from up arrow on disconnect/relog.

### Why should it be in the modpack

It's fairly annoying to accidentally disconnect, and lose access to an important command that you didn't save elsewhere.

### Why shouldn't it be in the modpack

I really can't think of any; this is quite simple, lightweight and vanilla-like.

### Categories

New feature

### Additional details

This is a fork of the mod with the same name on Curseforge. The fork updates and improves the original.

**Comment by Madis0** [comment]
Potential negatives:
* immersion breaking on hub-based servers (duplicate messages or some that just don't make sense in new context)
* increased cache sizes, maybe? haven't exactly tested how it works
* Modrinth-only mods make my management slightly harder, though not a deal-breaker as Indium and Hydrogen are already here

**Comment by wafflecoffee** [comment]
Oh look it's that mod I updated

> immersion breaking on hub-based servers

The mod name is actually a tad misleading if you don't know *which* chat history it's referring to (I didn't come up with the name): it doesn't change how the chat itself actually looks. The only thing it does is doesn't clear what is in your up arrow chat history.

> and whether it works on client restart

No

**Comment by Madis0** [comment]
> The mod name is actually a tad misleading if you don't know which chat history it's referring to (I didn't come up with the name): it doesn't change how the chat itself actually looks. The only thing it does is doesn't clear what is in your up arrow chat history.

Right, I was referring to something like being in a minigame and after rejoining it would mix that minigame chat with any hub messages. Though I'd say it's not a major issue.

> P.S.: for not clearing the chat history in the conventional definition, see MoreChatHistory

Ahh, that's interesting. Have you considered a PR to merge the two?

**Comment by Madis0** [comment]
On a related note, original mod was just updated 😁 
https://www.curseforge.com/minecraft/mc-mods/dont-clear-chat-history

**Comment by fredster33** [comment]
That might be favorable as it's on Curseforge :)
