### ISSUE TITLE
Chat Heads

### ISSUE THREAD

**Issue by itsmeboy0** [Madis0/fabulously-optimized#125]
### Mod name

Chat Heads

### Curseforge link

https://www.curseforge.com/minecraft/mc-mods/chat-heads

### Other links

https://github.com/dzwdz/chat_heads

### What it does

Clientside mod that adds player heads next to chat messages:

![chat-heads](https://user-images.githubusercontent.com/75471378/132939883-92bf04a6-9dae-4f72-861b-12074e5b7641.png)

### Why should it be in the modpack

> It makes telling various people in chat apart a bit easier, and it just looks nice.

### Why shouldn't it be in the modpack

None other than it is yet to be updated to [1.17](https://github.com/dzwdz/chat_heads/pull/13)

### Categories

Graphics optimization, New feature

**Comment by Madis0** [comment]
Does it work on non-vanilla servers?

**Comment by itsmeboy0** [comment]
> Does it work on non-vanilla servers?

Yes, it does.

**Comment by Madis0** [comment]
Interesting. I am a bit worried about it increasing the clutter on servers with long prefixes, but it might be a good addition still.

**Comment by Madis0** [comment]
I've decided against this as it is a stylistic choice that does not look like vanilla. It would make more sense for users to install it manually.
