### ISSUE TITLE
More Chat History

### ISSUE THREAD

**Issue by Madis0** [Madis0/fabulously-optimized#126]
### Mod name

More Chat History

### Curseforge link

https://www.curseforge.com/minecraft/mc-mods/more-chat-history

### Other links

https://modrinth.com/mod/morechathistory
https://github.com/JackFred2/MoreChatHistory

### What it does

Increases chat scroll limit from 100 lines to 16384

### Why should it be in the modpack

Major UX benefit, 100 lines are too little

### Why shouldn't it be in the modpack

Increased cache size? I think vanilla logs the chat in it's entirety anyway but I forgot, where

### Categories

New feature

### Additional details

Suggested in #123

**Comment by Rajbir98** [comment]
I don't think it will be good for low end devices but if there are way to make this mod optional that's good

**Comment by Madis0** [comment]
I'll see how it works, I presume it uses the logs that already exist though, so it shouldn't affect low-end devices more than others.

**Comment by Madis0** [comment]
Seems like the limit could be even higher, presumably it was just chosen as a balance between usability and performance. Tested with a repeating command block and as assumed, saw no difference in performance.

**Comment by Rajbir98** [comment]
ok if it doesnt affect performance its good

**Comment by Rajbir98** [comment]
I Have Opened a new mod request which is also based on chat improvement
#128
