### ISSUE TITLE
Show mods' main features and options in Mod Menu

### ISSUE THREAD

**Issue by Madis0** [Madis0/fabulously-optimized#127]
### What config to change

* Mod Menu to use standard list
  * Hide fabric-language-kotlin, indium
  * Count children mods
* Bundle the following resource pack (see below)
* Use YOSBR to default-enable it

### Why should it be changed

Pros:
* Users can easily know what each mod does
* Works in all languages
* Can be translated to all languages

Cons:
* Limited space
* Increased maintenance

### Category

Other

### Additional details

This is how it would look like:
![image](https://user-images.githubusercontent.com/8611110/133128335-ca7a1faa-5e5e-496e-b140-1a0d9e947b98.png)

Please test it out and give any feedback about this idea (e.g. colors, icons, format...).

V1 (prototype, changes both short and long description): [Mod-helper.zip](https://github.com/Madis0/fabulously-optimized/files/7149676/Mod-helper.zip)
V2 (prototype, changes only short description): [Mod-helper-v2.zip](https://github.com/Madis0/fabulously-optimized/files/7149706/Mod-helper-v2.zip)
V3 (adds all mods, simplifies formatting): [Mod-helper-v3.zip](https://github.com/Madis0/fabulously-optimized/files/7156215/Mod-helper-v3.zip)
V4 (shortened and simplified text): [Mod-helper-v4.zip](https://github.com/Madis0/fabulously-optimized/files/7172067/Mod-helper-v4.zip)

**Comment by Rajbir98** [comment]
looks good I will try it and edit this comment

**Comment by RozeFound** [comment]
The third variant looks great, but additional info (purple pencil) must be way shorter, to fit all screens.

**Comment by Madis0** [comment]
Thanks, uploaded v4 with simplified text. 
The second row does not actually have to fit fully as it's just a subset of what's available anyway, but it would be nice if it would be displayed to some extent and that is the case now.

**Comment by RozeFound** [comment]
Whoops, I didn't understand for what the second row is needed. Now when you changed "none" to "no options" that's more intuitive

**Comment by RozeFound** [comment]
It's only english now?

**Comment by Madis0** [comment]
> It's only english now?

For now, yes. I will translate it to my language when I'll release this and then everyone can contribute translations as well.

**Comment by RozeFound** [comment]
So, looks pretty good, I don't have anything to add
