### ISSUE TITLE
CompactChat

### ISSUE THREAD

**Issue by Rajbir98** [Madis0/fabulously-optimized#128]
### Mod name

CompactChat

### Curseforge link

N/A

### Other links

Modrinth: https://modrinth.com/mod/compactchat
Github: https://github.com/cbyrneee/CompactChat

### What it does

If a message is sent twice, the previous message will be removed, and the newer one will have the number of occurrences appended to it.
Make the chat look cleaner

### Why should it be in the mod pack

Clean up your chat by removing duplicate messages!
### Why shouldn't it be in the mod pack

not available in curse forge

### Categories

Graphics optimization, New feature, Replace an existing mod request

### Additional details

![preview](https://user-images.githubusercontent.com/84771149/133419962-8fa79225-3161-4dcd-9b18-02f2c6122f11.gif)
By default, CompactChat will automatically set your chat history's length to be infinite. This can be disabled via a config screen which can be opened with ModMenu.
So It Cant Also Replace More Chat History Mod

**Comment by Madis0** [comment]
I've heard from somewhere (similar older mod I think) that this kind of merging has performance implications. It might also interfere with intentional empty rows (in minigames, ads etc).

**Comment by Rajbir98** [comment]
by mistake i closed this issue mis click

**Comment by Rajbir98** [comment]
> I've heard from somewhere (similar older mod I think) that this kind of merging has performance implications. It might also interfere with intentional empty rows (in minigames, ads, etc).

I Noticed One more thing this by default sets chat history to infinite means it will not clear chat history but can be turned off in the mod menu so it can replace your mod request #126

**Comment by RozeFound** [comment]
"Not that useful" mod. It will help you recognize spam, and will clear a bit chat on some RPG servers. That's all. If ads going with one message (I don't know if minecraft have multiline messages...), it will be ok, but multi-message ads will be broken in 73% chance. 

What about performance hit, I haven't noticed any.

So, I don't recommend this mod to all.

**Comment by Madis0** [comment]
Rejected because:
* Changes vanilla behaviour, spam prevention or merging should be done server-side
* Separate messages are better for getting attention when needed (e.g command blocks)
* Breaks newlines in ads and other informational messages
* May affect performance (unverified)
