### ISSUE TITLE
Language Reload

### ISSUE THREAD

**Issue by Deathstar8** [Madis0/fabulously-optimized#129]
### Mod name

Language Reload

### Curseforge link

N/A

### Other links

https://modrinth.com/mod/language-reload
https://github.com/Jerozgen/LanguageReload

### What it does

Allows instantaneous switching between languages, removing the loading screen found in vanilla entirely. Also allows reloading of languages without resource pack reload via F3+J.

### Why should it be in the modpack

I believe it is a better alternative to Lazy-Language-Loader in that it switches languages faster than it, reducing the time players wait for the languages to change.

### Why shouldn't it be in the modpack

~~The mod is not available on Curseforge.~~ Has been confirmed by mod author to have been submitted to Curseforge and is awaiting approval by a moderator.

### Categories

Performance optimization

**Comment by Rajbir98** [comment]
Looks nice
let me use this 
I will inform you how was my experience

**Comment by RozeFound** [comment]
It's not faster than #124, but it feels faster because of removing loading screen. I'm not a fan of removing loading screens and fade animation in this modpack, but when loading is less than a second, it make sense.

Language reloading... I don't know where it can be useful.

**Comment by Madis0** [comment]
> I'm not a fan of removing loading screens and fade animation in this modpack

In some programs, the lack of animation really feels jarring. In Minecraft: Java Edition though, I feel like many people have already gotten used to having no animations (in contrast to Bedrock Edition, which uses a lot of animations), so it makes sense to remove the splash screen one as well for giving the perception of faster speed.

Anyway, this mod looks great and I will definitely add it once it is in CF.
