### ISSUE TITLE
TexTweaks

### ISSUE THREAD

**Issue by Madis0** [Madis0/fabulously-optimized#13]
**Mod name**
TexTweaks

**Curseforge link**
https://www.curseforge.com/minecraft/mc-mods/textweaks

**Modrinth link**
N/A

**Other link**
https://github.com/UltimateBoomer/mc_textweaks

**What it does**
Something with texture scaling

**Why should it be in the modpack**
Optifine parity, I think

**Why shouldn't it be in the modpack**
Haven't tested, no idea how to use or if it can benefit everyone at all

**Categories**

- [ ] Performance optimization
- [x] Graphics optimization
- [ ] New feature
- [x] Optifine parity
- [ ] Fixes a bug/dependency

**Additional details**

**Comment by CodeF53** [comment]
Perhaps the pack should come with a pre-configured options for this.

It still offers a performance benefit when set up correctly

**Comment by Madis0** [comment]
@CodeF53 Please elaborate, how did you set it up and how (much) did it improve your performance.

**Comment by CodeF53** [comment]
Let me quickly test that

**Comment by CodeF53** [comment]
Enabled I get an average of 875 FPS.
Disabled I get an average of 840 FPS.

Testing this now, the gains are much less significant than I remember.

Here is a screenshot of my config:
![image](https://user-images.githubusercontent.com/37855219/122902509-bd5cab00-d30b-11eb-9fe2-afddfccef18c.png)

**Comment by Madis0** [comment]
Hmm, okay. Here's what I gathered:
* The main changed thing here is additional mipmapping; mipmapping exists in vanilla but there it only works for 16x resource packs.
* If I included this with "optimized" settings, it could look wrong with some resource packs and high-resolution screens - that is not what I want as a default.
* LOD bias seems like something that users could adjust wrong and therefore get extreme blur or pixelation
* "Optifine is needed for foliage to be correctly mipmapped"

So in the end, if there will ever be some kind of "easy mode" - you know, one or two sliders like Optifine, then I could reconsider it. Right now it is still too confusing to expect users to modify it, or if I modify it for them - could disrupt their view.

**Comment by Rajbir98** [comment]
can we make a config file in which all setting is preloaded so that people donot have to modify it

**Comment by CodeF53** [comment]
I will do a bit of experimenting for a general purpose config file for the mod.

I am not quite sure how you would deploy config files with a modpack.

**Comment by Madis0** [comment]
> can we make a config file in which all setting is preloaded so that people donot have to modify it

> I am not quite sure how you would deploy config files with a modpack.

That's one of the points of a modpack, to configure mods for a specific purpose :D So yes, config files can absolutely be included.

However, my point is that if the player is using a "non-standard" setup like a 4K or Retina screen, then they must understand how the settings work to revert it at least. And as of now, even I don't fully understand how the settings work.

So as I suggested previously, if you can convince the mod owner of including an "easy mode" of some kind or simply could help them rephrase the settings for better understanding, then I could include this eventually.

**Comment by Rajbir98** [comment]
Asking For Fps Boost Settings https://github.com/UltimateBoomer/mc-textweaks/issues/9#issue-1000219828

**Comment by Rajbir98** [comment]
Asking For Easy Mode https://github.com/UltimateBoomer/mc-textweaks/issues/10#issue-1004104679

**Comment by Calardaras** [comment]
> Hmm, okay. Here's what I gathered:
> 
> * The main changed thing here is additional mipmapping; mipmapping exists in vanilla but there it only works for 16x resource packs.
> * If I included this with "optimized" settings, it could look wrong with some resource packs and high-resolution screens - that is not what I want as a default.
> * LOD bias seems like something that users could adjust wrong and therefore get extreme blur or pixelation
> * "Optifine is needed for foliage to be correctly mipmapped"
> 
> So in the end, if there will ever be some kind of "easy mode" - you know, one or two sliders like Optifine, then I could reconsider it. I don't really know what kind of algorithm or presets to use for making it simple, so at the moment I cannot suggest it to the author either.
> 
> Right now it is still too confusing to expect users to modify it, or if I modify it for them - could disrupt their view.

Some Resource packs will cause vanilla mipmapping to break due to 1*1 pixel texture. Continuity's author affirmed this issue. Optifine fixes this issue by upscaling textures. In fabric, TexTweaks is the only mod that can upscale textures. Both performance and visual looking would have a significantly improved by using TexTweaks.

**Comment by Madis0** [comment]
Again, I believe adding the mod could benefit, but at the moment it would only benefit those who can properly configure it for their setup because the settings are so complex.

**Comment by CodeF53** [comment]
Generally doesn't matter because the mod hasn't been updated since 1.17, and forks don't go to 1.19
