### ISSUE TITLE
When modpack is loading the loading process stops then it application stops responding and crashes.

### ISSUE THREAD

**Issue by EpicDrag0n** [Madis0/fabulously-optimized#130]
### Describe the bug

I have tried MultiMc and curseforge app but it didn't work, once I start the modpack it just stays on the mojang studios loading screen and once you click on it it just stops responding and crashes I am using the latest version of the modpack. 

### Expected behavior

I am suppose to see the game start up.

### Observed/actual behavior

The game is not loading.

### Steps To Reproduce

1. Launched Minecraft
2. game stops loading
3. crashes upon clicking on it

### Modpack version

The latest one

### Launcher

MultiMC

### Install method

Fresh install/new profile

**Comment by Madis0** [comment]
Interesting. Please paste the launcher log or crash log to [Pastebin](https://pastebin.com/) and post the link here.

**Comment by Rajbir98** [comment]
Weird Doesn't happens to me I am using vanilla launcher

**Comment by EpicDrag0n** [comment]
ok I think i've found the problem for some reason sodium version 0.3.2  crashes my game so once I used 0.3.0 it worked

**Comment by Madis0** [comment]
In that case, please report it to Sodium so they could fix it.

**Comment by EpicDrag0n** [comment]
ok
