### ISSUE TITLE
Translucent/See through textures

### ISSUE THREAD

**Issue by Furiad** [Madis0/fabulously-optimized#131]
### Describe the bug

Shulker boxes and entity skins (example: villagers, zombies) are are translucent/see through.

### Expected behavior

Solid with no translucency

### Observed/actual behavior

Translucent/inverted textures/ski
![2021-09-18_09 21 27](https://user-images.githubusercontent.com/90973244/133892020-56f50afd-12e7-429e-95b7-a674c19df149.png)
![2021-09-18_09 22 03](https://user-images.githubusercontent.com/90973244/133892025-eee3961f-48fd-44e8-ab02-e47320c5c20e.png)
ns

### Steps To Reproduce

Launched CurseForge
Loaded Pack
Logged in
Joined Server

### Modpack version

2.1.1

### Launcher

Curseforge Launcher

### Install method

Fresh install/new profile

**Comment by Madis0** [comment]
I can see in the first screenshot that you have more mods than there are by default in the modpack. Try disabling all additional mods and re-enabling them one by one to see which mod creates the issue.

**Comment by Furiad** [comment]
Bounding Box Reloaded was causing the issue. Thanks
