### ISSUE TITLE
Use Fabric's default Java arguments on MultiMC

### ISSUE THREAD

**Issue by Rajbir98** [Madis0/fabulously-optimized#134]
### What config to change

`-Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M`

### Why should it be changed

It Improves My Fps from 60 to 80 Made My Game Smooth With No Spikes

### Category

Other

### Additional details

I Have Removed The RAM Allocation Part To Make Sure It Would Be Easier To Add This As Everone's System Is Not Same

**Comment by Madis0** [comment]
Hmm. I think I can only change it on MultiMC but even then I am wary because I don't know what all flags do, and why set exactly these values to them.

Do you have a source on which you based the suggestion for?

**Comment by Rajbir98** [comment]
Yes I Have Just Taken These From This Github Post https://github.com/PojavLauncherTeam/PojavLauncher/issues/668
As The Comments Of The Post And MY Expirence I Thought I Should Share THis To You @

**Comment by Madis0** [comment]
https://xealgaming.net/threads/optimising-your-minecraft-jvm-arguments.4758/
This is the source link (from the issue).

**Comment by Rajbir98** [comment]
> https://xealgaming.net/threads/optimising-your-minecraft-jvm-arguments.4758/
> This is the source link (from the issue).
According to https://xealgaming.net/threads/optimising-your-minecraft-jvm-arguments.4758/ 

> Important Things to Note
"-Xmx3G -Xms3G -Xmn768m" tells Minecraft to use 3GB of RAM. If you have less than 4GB of RAM, DO NOT use this. Always ensure that your system has at least 2GB of RAM leftover. Never use ALL the RAM or your computer will crash.
"-XX:ReservedCodeCacheSize=2048m" tells Minecraft to reserve 2GB of RAM for storing code that might be used again. If you allocated 2GB of RAM to Minecraft, you need to reduce the number here to half of that, which is 1024m for example.
"-XX:SoftRefLRUPolicyMSPerMB=10000" keeps the soft reference to 10 seconds per MB. If it lags your computer, feel free to reduce the number of removing the line entirely.

> I Have Removed All Memory Depenciences

**Comment by Madis0** [comment]
I tried this with vanilla launcher and non-FO profile and just got an instant crash - a clear note that this shouldn't be enabled for everyone as a whole - maybe only some parts of it.

Also, from brief glance there are flags that are just bad (`-Dfml.ignoreInvalidMinecraftCertificates=true`) and some that [are deprecated](https://stackoverflow.com/questions/49962437/unrecognized-vm-option-useparnewgc-error-could-not-create-the-java-virtual) (`-XX:+UseParNewGC`) - more research is needed.

This is Fabric's default set BTW:

```
-Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
```

**Comment by Deathstar8** [comment]
JVM arguments don't fit everyone, but the one that is shipped with Fabric by default is made to fit the most overall. I think for simplicity's sake we should just use those JVM arguments. People can change these arguments on their own if they want to.

**Comment by Rajbir98** [comment]
> I tried this with vanilla launcher and non-FO profile and just got an instant crash - a clear note that this shouldn't be enabled for everyone as a whole - maybe only some parts of it.
> 
> Also, from brief glance there are flags that are just bad (`-Dfml.ignoreInvalidMinecraftCertificates=true`) and some that [are deprecated](https://stackoverflow.com/questions/49962437/unrecognized-vm-option-useparnewgc-error-could-not-create-the-java-virtual) (`-XX:+UseParNewGC`) - more research is needed.
> 
> This is Fabric's default set BTW, maybe that should be used for MultiMC as well.
> 
> ```
> -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
> ```

ok

**Comment by Rajbir98** [comment]
let me update the issue to remove that argument and use the fabric one

**Comment by Rajbir98** [comment]
> I tried this with vanilla launcher and non-FO profile and just got an instant crash - a clear note that this shouldn't be enabled for everyone as a whole - maybe only some parts of it.
> 
> Also, from brief glance there are flags that are just bad (`-Dfml.ignoreInvalidMinecraftCertificates=true`) and some that [are deprecated](https://stackoverflow.com/questions/49962437/unrecognized-vm-option-useparnewgc-error-could-not-create-the-java-virtual) (`-XX:+UseParNewGC`) - more research is needed.
> 
> This is Fabric's default set BTW, maybe that should be used for MultiMC as well.
> 
> ```
> -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
> ```

According to https://xealgaming.net/threads/optimising-your-minecraft-jvm-arguments.4758/
 ensure that you are running on the latest version of Java 8.
Which might be the problem i am using Tlauncher and configure java16 so it worked for me ok well no need to make it complicated i just update the issue and added the fabric default arguments

**Comment by Madis0** [comment]
> ensure that you are running on the latest version of Java 8.
> This might be the problem I am using Tlauncher and configured Java 16

Well, Minecraft 1.17 doesn't run on Java older than 16 so it's just the instructions that are old 😁 

But yeah, it probably doesn't hurt to use Fabric's defaults on MultiMC profile so I'll do that on next release.
