### ISSUE TITLE
 Detail Armor Bar

### ISSUE THREAD

**Issue by RozeFound** [Madis0/fabulously-optimized#138]
### Mod name

 Detail Armor Bar

### Curseforge link

https://www.curseforge.com/minecraft/mc-mods/detail-armor-bar

### Other links

https://modrinth.com/mod/detail-armor-bar
https://github.com/RedLime/DetailArmorBar

### What it does

Adds more information to the armor bar. Make it looks pretty and useful

### Why should it be in the modpack

Improves UX and UI a bit

### Why shouldn't it be in the modpack

Not really vanilla-like

### Categories

Graphics optimization

**Comment by Madis0** [comment]
Looks cool but is out of scope for the pack.
