### ISSUE TITLE
RetiNO

### ISSUE THREAD

**Issue by NebelNidas** [Madis0/fabulously-optimized#143]
### Mod name

RetiNO

### Curseforge link

https://www.curseforge.com/minecraft/mc-mods/retino

### Other links

https://github.com/juliand665/retiNO

### What it does

> This mod makes Minecraft render at half resolution on Retina displays, which is probably enough for you anyway and has the advantage of not murdering your performance and its extended family.
> 
> This mod only affects macOS (although it runs just fine on other platforms; it simply doesn't do anything)

### Why should it be in the modpack

#142 hasn't been accepted because it has to be configured manually by the user, and being too confusing. RetiNO automatically applies its changes, and only to Macs with Retina display, where it's actually needed.

### Why shouldn't it be in the modpack

No reason. If you don't have a Retina display, it simply doesn't do anything, and if you have one, you won't notice the reduced resolution anyway (even Canvas applies this patch by default).

### Categories

Performance optimization, Graphics optimization

**Comment by Madis0** [comment]
The option [already exists in Sodium Extra](https://www.curseforge.com/minecraft/mc-mods/sodium-extra/files/3442217), are you sure it is needed?

**Comment by RozeFound** [comment]
> The option already exists in Sodium Extra, are you sure it is needed?

In Sodium Extra this is an option, in this mod all works automatically. 
I think it's the main purpose of this request.

**Comment by TheMadHau5** [comment]
It's enabled by default in this pack, so it doesn't matter anyways. I suggest this issue be closed.

**Comment by Madis0** [comment]
It also [gets automatically disabled on non-Macs](https://github.com/FlashyReese/sodium-extra-fabric/commit/dbd213f8e0f656786820c370f4231e653ac9d8c4) in the next version.
