### ISSUE TITLE
MultiMC auto-updater is not installing mods.

### ISSUE THREAD

**Issue by Carl1590** [Madis0/fabulously-optimized#146]
### Describe the bug

When the auto-updater zip is used to make a profile in MultiMC and launched, Minecraft runs normally with Fabric, but with no mods.

### Expected behavior

Packwiz should run and install the modpack.

### Observed/actual behavior

Packwiz does not run. I've also noticed that the:

`PreLaunchCommand="$INST_JAVA" -jar packwiz-installer-bootstrap.jar https://raw.githubusercontent.com/Madis0/fabulously-optimized/main/Packwiz/1.17.1/pack.toml`

line in the instance.cfg is removed when the instance is run. This could be what is causing this, but I'm not sure why it gets removed.

### Steps To Reproduce

1. Made an instance in MultiMC using the auto-updater zip
2. Launched the instance
3. Minecraft runs normally with Fabric, but with no mods

### Modpack version

2.2.0

### Launcher

MultiMC

### Install method

Fresh install/new profile

### Additional context

Previous versions of the auto-updater work just fine.

**Comment by nchristopher** [comment]
If you go into **Edit instance** > **Settings** > **Custom commands**, then paste `"$INST_JAVA" -jar packwiz-installer-bootstrap.jar https://raw.githubusercontent.com/Madis0/fabulously-optimized/main/Packwiz/1.17.1/pack.toml` into **Pre-launch command**, does it work?

**Comment by Carl1590** [comment]
> If you go into **Edit instance** > **Settings** > **Custom commands**, then paste `"$INST_JAVA" -jar packwiz-installer-bootstrap.jar https://raw.githubusercontent.com/Madis0/fabulously-optimized/main/Packwiz/1.17.1/pack.toml` into **Pre-launch command**, does it work?

Thank you, your solution worked! Now, I'm wondering why the Pre-launch command isn't set, even though its in the instance.cfg? Or am I missing something?

**Comment by nchristopher** [comment]
🤔 That's strange. If it's defined in `instance.cfg` it should work, it might've just not properly loaded that time. When you were experiencing this issue, did you try restarting MultiMC at all? Did it persist?

**Comment by Carl1590** [comment]
I've already tried restarting MultiMC multiple times and it hasn't worked, although I am on the MultiMC development update channel. I'll see if switching to stable does anything.

**Comment by Carl1590** [comment]
Switching to the stable channel didn't make a difference. I also noticed that if you go to Edit Instance then close the window that pops up, the pre-launch line in instance.cfg disappears, if that is useful information.

**Comment by Madis0** [comment]
Ugh, it might be that JVM args conflict with the pre-launch commands.
This version should work: https://github.com/Madis0/fabulously-optimized/releases/download/v2.1.0/Fabulously.Optimized.MultiMC.auto-update.zip
I'll revert it in the readme and investigate more.

**Comment by Madis0** [comment]
The issue has been fixed and it has been reuploaded to https://github.com/Madis0/fabulously-optimized/releases/download/v2.2.0/Fabulously.Optimized.MultiMC.auto-update.1.17.1.zip
Sorry for the inconvenience.
