### ISSUE TITLE
Starline

### ISSUE THREAD

**Issue by user859347** [Madis0/fabulously-optimized#147]
### Mod name

Iris (Starline)

### Other links

https://github.com/HyperCubeMC/Iris

### What it does

Starline is a fork of Iris that adds shader settings

### Why should it be in the modpack

Many people want to customize their shaders.

### Why shouldn't it be in the modpack

Not available in Curseforge

### Categories

Replaces an existing mod

### Additional details

It also needs a custom sodium version: https://github.com/HyperCubeMC/sodium-fabric

**Comment by Madis0** [comment]
Starline is made of experimental and outdated pull requests to Iris. It is unsustainable and potentially unstable, therefore not recommended to use.
(info sourced from [Iris's Discord](https://discord.gg/jQJnav2jPu))

Besides, the proper configuration system is already being built to Iris. If you want to support these efforts, please [donate to Iris](https://www.patreon.com/coderbot).
