### ISSUE TITLE
EnhancedBlockEntities

### ISSUE THREAD

**Issue by Madis0** [Madis0/fabulously-optimized#23]
**Mod name**
EnhancedBlockEntities

**Curseforge link**
https://www.curseforge.com/minecraft/mc-mods/enhanced-block-entities

**Modrinth link**

**Other link**
https://github.com/FoundationGames/EnhancedBlockEntities

**What it does**
Same as FastChest but with animations and support for other blocks in the future

**Why should it be in the modpack**
More optimizations than FastChest

**Why shouldn't it be in the modpack**
Requires Rendering API

**Categories**

- [x] Performance optimization
- [ ] Graphics optimization
- [ ] New feature
- [ ] Optifine parity
- [ ] Fixes a bug/dependency
- [x] Replaces an existing mod

**Additional details**

https://github.com/FoundationGames/EnhancedBlockEntities/issues/31

**Comment by Samisaprogrammer** [comment]
I will mention EBE has a few issues with mod compatibility, namely replay mod. See FoundationGames/EnhancedBlockEntities#31 for details.

**Comment by Madis0** [comment]
Thanks for the heads up, that is indeed an important bug that could affect any mod that uses resource packs. I will revert the changes of beta 3 and postpone EBE for later.

**Comment by Deathstar8** [comment]
> Q: Does this mod glitch the chest animation or turn chests invisible? A: This bug has been completely eradicated in EBE versions 0.5 and above. If the issue still persists (it shouldn't), leave an issue on GitHub or join the Discord Server.

According to the mod author, the bug has been fixed in the latest versions. I did some tests with replay mod and didn't encounter the bug. Not sure why the issue on their page is still open though.
