### ISSUE TITLE
RandomPatches

### ISSUE THREAD

**Issue by Madis0** [Madis0/fabulously-optimized#26]
**Mod name**
RandomPatches

**Curseforge link**
https://www.curseforge.com/minecraft/mc-mods/randompatches-fabric

**Modrinth link**

**Other link**
https://github.com/TheRandomLabs/RandomPatches/tree/1.16-fabric#randompatches-fabric

**What it does**
Fixes Minecraft's bugs

**Why should it be in the modpack**
Some fixes may be relevant to everyone

**Why shouldn't it be in the modpack**
Haven't found any relevant fixes yet

**Categories**

- [x] Performance optimization
- [x] Graphics optimization
- [ ] New feature
- [ ] Optifine parity
- [x] Fixes a bug/dependency
- [ ] Replaces an existing mod

**Additional details**

**Comment by Madis0** [comment]
@abasgames You are suggesting this mod because of the keepalive feature, however this feature is claimed to be server-side, so it wouldn't help in most servers. Please elaborate your request.

**Comment by 12emin34** [comment]
This can be closed, that feature is server-side. The server sends a keepalive packet to the client ocassionally to see if the client is still listening to the connection, and if not the client is kicked. This can annoy players with bad internet connections. To fix this you can change the keepalive system to work in a better way like RandomPatches and Purpur do, but it cannot be changed from the client AFAIK.
