### ISSUE TITLE
Options.txt

### ISSUE THREAD

**Issue by Madis0** [Madis0/fabulously-optimized#30]
What options should be changed as a default to warrant including an options.txt (as default or with a delta diff mod)? 

Current ideas:
- Disable autojump - `autoJump true`
- No third-party warning - `skipMultiplayerWarning true`
- No starting tutorial - `tutorialStep none`
- GUI scale 3? - `guiScale 3`
- B/W title screen (1.17)? - `darkMojangStudiosBackground‌ true`
- Zoom key
- ...  

Also I need to make a wiki page describing the changes.

**Comment by Luligabi1** [comment]
Hi, I'm the author of the mod suggested on #29 , I was contacted by the maker of the original issue. Most of these could be implemented without much work, with the exception of:

> No third-party warning
This most likely violates Mojang's TOS as the warning exists for legal reasons.

> Zoom key
I'm currently only supporting vanilla settings to avoid external libraries and stuff that might only work for one mod but not the other.

Answering to your comment  `but why music?` on #29 :

It was done mostly by asking some friends if they disabled the music entirely as well. Keep in mind that the mods has a configuration file (located at ./minecraft/config/noannoyingsettings.properties) that allows to toggle if the mod should force any of it's options into you. If you end up including the mod on the modpack, you might bundle the config file with the `disableMusic `setting to `false`.

Regardless, thank you for the suggestions! I'll be shipping an update to the mod including some of your suggestions very soon.

**Comment by Luligabi1** [comment]
Out now: https://www.curseforge.com/minecraft/mc-mods/no-annoying-settings/files/3236341 

Tutorial skip, gui scale and subtitle (by default off) settings are now included.

**Comment by Madis0** [comment]
@Luligabi1 

Wow. I guess I should apologize for the confusion as the intention was not to contact you at all 😄 

Your mod does what it says, it is just unsuitable for this pack as it forces the values on every restart, which is not what I want, I want just the defaults. I do see value in your mod for people that use other modpacks and always want their settings though.

This issue was to discuss or at least list the things I could change in my modpack. Similarly, "zoom key" referred to the mod in this modpack and not adding a new feature.

Pinging @andytxr as well to notify of this.

**Comment by Luligabi1** [comment]
> Wow. I guess I should apologize for the confusion as the intention was not to contact you at all, otherwise I would've made an issue in your repo instead smile
> 
> Your mod does what it says, it is just unsuitable for this pack as it forces the values on every restart, which is not what I want, I want just the defaults. I do see value in your mod for people that use other modpacks and always want their settings though.
> 
> This issue was to discuss or at least list the things I could change in my modpack. Similarly, "zoom key" referred to the mod in this modpack and not adding a new feature.

I guess I should apologize as this is more of an interpretation issue on my end. I'm completely fine with the mod not being included on the modpack. At the end, it comes to your own judgment of what's better for the pack and the feel you're going with it. Thank for your suggestions for the mod, as they really were missing!

**Comment by NebelNidas** [comment]
My recommendations are:
- `guiScale:2`: That's the normal size Minecraft should be run at on a non-HiDPI display
- `gamma:0.5`: Good middle-ground between 0% and 100% brightness
- `fov:0.5`: 90° FOV is what many first-person games have today. If it's too extreme for you, 80° (`fov:0.25`) would also be ok, but Minecraft's default 70° are definitely too low.

**Comment by srnyx** [comment]
> * `fov:0.5`: 90° FOV is what many first-person games have today. If it's too extreme for you, 80° (`fov:0.25`) would also be ok, but Minecraft's default 70° are definitely too low.

Wouldn't you want the FOV to be lower? The higher the FOV the laggier it is.

**Comment by Madis0** [comment]
> > * `fov:0.5`: 90° FOV is what many first-person games have today. If it's too extreme for you, 80° (`fov:0.25`) would also be ok, but Minecraft's default 70° are definitely too low.
> 
> Wouldn't you want the FOV to be lower? The higher the FOV, the laggier it is.

Good point, I set it to 80° but will revert in the next update.

**Comment by TheMadHau5** [comment]
In my experience, the performance decrease caused by a higher FOV is negligible, so 90° would be the best IMHO.

**Comment by srnyx** [comment]
> In my experience, the performance decrease caused by a higher FOV is negligible, so 90° would be the best IMHO.

Well it on depends on the person's computer. So, if a player has a better computer they can turn it up themselves, there's no reason they can't. But, since this modpack has the intention to reduce lag, it's probably better not to change the FOV.

**Comment by CodeF53** [comment]
I feel like there should be presets for options.txt

Most optimized, and Recommend

**Comment by Madis0** [comment]
@CodeF53 I don't know how you could swap between them though. Perhaps your suggestion would suit better in Sodium Extra, as that adds new graphics options which could have presets.

**Comment by nsde** [comment]
The Modpack's name is "Fabulously-Optimized", maybe lower graphic settings?
We should find a good compromise between performance and looks.
Maybe fast but with cull/"smart" leaves, so players can still see through leaves.
Vignette turned off, same with Fog. Both can cause performance issues.

**Comment by Madis0** [comment]
> The Modpack's name is "Fabulously-Optimized", maybe lower graphic settings? We should find a good compromise between performance and looks. Maybe fast but with cull/"smart" leaves, so players can still see through leaves. Vignette turned off, same with Fog. Both can cause performance issues.

I did experiment with it to an extent, as you can see from [2.0.0b4](https://github.com/Fabulously-Optimized/fabulously-optimized/blob/main/CHANGELOG.md#200b4-2021-07-01) and higher. But even reducing particles had unintended consequences, as Sodium Extra is providing options for the individual particle settings.

Vignette and fog - well, they break the vanilla look and look weird when disabled by default. As you said, I want the balance, rather than just the "best FPS possible".

In any case, for new option changes please create a new issue (and separate issues for each option you want to change).
