### ISSUE TITLE
MiniHUD

### ISSUE THREAD

**Issue by JDar2K** [Madis0/fabulously-optimized#31]
**Mod name**
MiniHUD

**Curseforge link**
https://www.curseforge.com/minecraft/mc-mods/minihud

**Modrinth link**
Optional, may become useful in the future when Modrinth adds modpack support.

**Other link**

**What it does**
"A client-side mod that allows displaying various "info lines" on the screen ("mini-F3")." - modpage. Includes smaller hud tweaks such as Beeinfo and ShulkerTooltips in to a singular mod

**Why should it be in the modpack**
Combines many small client -ide mods into one mod.

**Why shouldn't it be in the modpack**
Requires the MaLiLib library mod and is only client-side, no server support for now.

**Categories**

- [ ] Performance optimization
- [ ] Graphics optimization
- [x] New feature
- [ ] Optifine parity
- [ ] Fixes a bug/dependency
- [ ] Replaces an existing mod

**Additional details**

**Comment by Madis0** [comment]
Hmm. To me it seems like the mod provides just text labels on the screen, which Sodium Extra already does in this modpack (coordinates and FPS, which are useful for most). 
But you also claim that it provides "smaller HUD tweaks like Beenfo and ShulkerTooltips" - can you give a screenshot? I don't see anything like that written or pictured in the mod page.

**Comment by JDar2K** [comment]
![javaw_iTxDYlV8rf](https://user-images.githubusercontent.com/39681015/111519594-42d92980-8725-11eb-861c-590e44d438bf.png)
![javaw_NmPLWo73Iv](https://user-images.githubusercontent.com/39681015/111519604-44a2ed00-8725-11eb-8d8e-12499998ed70.png)
![javaw_U9WKARchiL](https://user-images.githubusercontent.com/39681015/111519607-453b8380-8725-11eb-8a45-e480b9bb60a3.png)
![javaw_Y1xkxEiISw](https://user-images.githubusercontent.com/39681015/111519608-453b8380-8725-11eb-913e-8eecb7153cd3.png)
![javaw_C9nBZn2bBC](https://user-images.githubusercontent.com/39681015/111519611-45d41a00-8725-11eb-8d15-e3e033ca08b6.png)

**Comment by Madis0** [comment]
Wow, that's a lot of options. I think I'll wait for 1.17 first though, maybe some of those will be added in vanilla for all.

**Comment by NebelNidas** [comment]
In my opinion this mod is out of scope for this modpack, it just overwhelms players with many confusing options (which was the reasoning behind closing #20, and most options are opt-in, which was why #42 was closed)

**Comment by Madis0** [comment]
To be clear, #42 was closed because the options are opt-in _per world_ (so I wouldn't be able to opt users in globally), not because they are opt-in overall.

I agree that there are way too many options in this mod, however it _may_  be worth considering because having one well-maintained (and well-compatible) mod could be better than multiple mods that need to be installed separately for the same goal - think of how Sodium Extra benefits the users right now.

**Comment by NebelNidas** [comment]
> think of how Sodium Extra benefits the users right now

Yeah, but that one just restores lost vanilla functionality (plus 3 or 4 extra options), while MiniHUD consists of a ton of extra features. I think it would be best to also declare this mod as an optional one 🤔

**Comment by JDar2K** [comment]
> I think it would be best to also declare this mod as an optional one
I understand this sentiment as I was originally not going to suggest this mod until I saw Shulker Tooltips was in consideration and thought, "If Shulker Tooltips were to be added and then later another mod was added that both could be replaced by a single mod I would like to bring MiniHUD to attention."

I think having the mod disabled in MultiMC thus making it optional or having the mod preconfigured would be the best use for MiniHUD.

**Comment by Madis0** [comment]
I've decided it is indeed too complex for the pack and added to [the won't-include list](https://github.com/Madis0/fabulously-optimized/wiki/Mods-that-won't-be-included) instead. Thanks for the suggestion!

**Comment by TheMadHau5** [comment]
> I think having the mod disabled in MultiMC thus making it optional or having the mod preconfigured would be the best use for MiniHUD.

This suggestion is still great and IMHO should be done, at least for other optional mods that you're okay with adding.

**Comment by Madis0** [comment]
@TheMadHau5 I have tried using optional mods at the start of this pack, the experience was not good (I think it didn't display them at all in the list). Surely things could have changed by now for CF but for MultiMC that would also mean increasing the file size for no reason. 
Besides, having "optional" stuff does complicate my maintenance further, considering that the mod list is growing overall and I do want to make the updates/install easier for users as well - no config overwrite, MultiMC pack updater, better vanilla launcher support - all those increase my maintenance a bit... So right now it is a no from me.

(If you wish to discuss this further, please create a new issue with elaborated details)

**Comment by CodeF53** [comment]
You should move Minihud to functional, and add all other Masa mods to the won't include list. 

Masa mods:
 - Tweakaroo
 - Litematica
 - MiniHud
 - Item Scroller.

**Comment by Madis0** [comment]
@CodeF53 Thanks, I'll move it soon. The list is not meant to be conclusive - it will only have the mods that _players suggest here_, so I'll not add the other four at the moment.

**Comment by CodeF53** [comment]
@Madis0 
> it will only have the mods that players suggest here

(I would've suggested all of them if this wasn't rejected for being too complex)
