### ISSUE TITLE
RecipeUnlocker

### ISSUE THREAD

**Issue by Madis0** [Madis0/fabulously-optimized#33]
**Mod name**
RecipeUnlocker

**Curseforge link**

**Modrinth link**

**Other link**
https://github.com/gbl/RecipeUnlocker

**What it does**
Removes the recipe unlocking mechanic

**Why should it be in the modpack**
Unlocking recipes makes no sense for survival Minecraft, only custom maps. This is evident by Bedrock Edition as well, where this feature does not exist.

**Why shouldn't it be in the modpack**
No license, not on CF, animations may distract, unlocking tooltips must still be disabled with another mod

**Categories**

- [ ] Performance optimization
- [ ] Graphics optimization
- [x] New feature
- [ ] Optifine parity
- [ ] Fixes a bug/dependency
- [ ] Replaces an existing mod

**Additional details**

Related: [I Am Very Smart](https://www.curseforge.com/minecraft/mc-mods/i-am-very-smart)

**Comment by TheMadHau5** [comment]
Please replace with I Am Very Smart, it's well known and widely used.

**Comment by Madis0** [comment]
Okay, I'll make a new issue for that.
This one is now rejected because it's closed, not in CF and abandoned.
