### ISSUE TITLE
Tic-TACS

### ISSUE THREAD

**Issue by Madis0** [Madis0/fabulously-optimized#34]
**Mod name**
Tic-TACS

**Curseforge link**

**Modrinth link**

**Other link**
https://github.com/Gegy/tic-tacs

**What it does**
Improves chunk generation and loading

**Why should it be in the modpack**
Makes chunk loading even faster

**Why shouldn't it be in the modpack**
Compatibility with CaffeineMC mods is unknown, experimental, chance of game freeze/crash, not on CF

**Categories**

- [x] Performance optimization
- [ ] Graphics optimization
- [ ] New feature
- [ ] Optifine parity
- [ ] Fixes a bug/dependency
- [ ] Replaces an existing mod

**Additional details**

**Comment by NebelNidas** [comment]
Isn't tic-tacs abandoned? If anything, I would go for C2ME: https://github.com/YatopiaMC/C2ME-fabric

**Comment by Madis0** [comment]
Thanks.
