### ISSUE TITLE
Better Beds

### ISSUE THREAD

**Issue by NebelNidas** [Madis0/fabulously-optimized#36]
**Mod name**
Better Beds

**Curseforge link**
https://www.curseforge.com/minecraft/mc-mods/better-beds

**Modrinth link**
N/A

**Other link**
https://github.com/TeamMidnightDust/BetterBeds

**What it does**
Removes the BlockEntityRenderer from the bed and replaces it with the default minecraft model renderer.
This results in increased performance and resourcepack support!

**Why should it be in the modpack**
Improves performance when looking at beds

**Why shouldn't it be in the modpack**
N/A

**Categories**

- [x] Performance optimization
- [x] Graphics optimization
- [ ] New feature
- [ ] Optifine parity
- [x] Fixes a bug/dependency
- [ ] Replaces an existing mod

**Comment by Madis0** [comment]
Beds seem like a very niche use case, so I'd hope to see it get merged in #23 instead. 

Unless you know of a good use case? I don't know even any minigame that would use a lot of beds at the same place.

**Comment by NebelNidas** [comment]
1) EBE doesn't support beds yet: https://github.com/FoundationGames/EnhancedBlockEntities/issues/8
2) Beds might be a niche, but why not take the free FPS? We newer know what users will play with this pack, and since BetterBeds has no drawbacks, I would certainly include it. The improvements are definitely measurable when looking at many beds, it's the same as FastChest 🤷‍♂️

**Comment by Madis0** [comment]
Well, the drawbacks of any mod are maintainability and compatibility. Every mod does potentially add another vector for bugs, crashes or simply glitches, so I try to go for mods that do add a benefit for most use cases.

E.g. for FastChest it obviously helps in chest rooms, a common part of a Minecraft base.

**Comment by NebelNidas** [comment]
- maintainability: You can remove BetterBeds at any time, it has no drawbacks like e.g. Starlight
- compatibility: I use the mod with 160+ other mods, and never noticed any compatibility issues. They could only occur if some mod would try to modify the default bed entity model (which no Fabric mod does atm.)

I would just add it until EBE supports this natively.

**Comment by Madis0** [comment]
Added
