### ISSUE TITLE
FerriteCore

### ISSUE THREAD

**Issue by NebelNidas** [Madis0/fabulously-optimized#38]
**Mod name**
FerriteCore

**Curseforge link**
https://www.curseforge.com/minecraft/mc-mods/ferritecore-fabric

**Modrinth link**
https://modrinth.com/mod/ferrite-core

**Other link**
https://github.com/malte0811/FerriteCore

**What it does**
Memory usage optimizations

**Why should it be in the modpack**
Drastically reduces amount of RAM used with no known incompatibilities.

**Why shouldn't it be in the modpack**
N/A

**Categories**

- [x] Performance optimization
- [ ] Graphics optimization
- [ ] New feature
- [ ] Optifine parity
- [ ] Fixes a bug/dependency
- [ ] Replaces an existing mod

**Additional details**
2.0.3 was partly incompatible with Hydrogen, but with 2.0.4 they are fully compatible.

**Comment by Madis0** [comment]
Interesting, should test this with and without Hydrogen.

**Comment by NebelNidas** [comment]
When choosing between the two, FerriteCore is better. But combined they're even better! Reduced my RAM usage from 1.5 GB to 0.9 GB

**Comment by Madis0** [comment]
Added
