### ISSUE TITLE
Lithium with Hopper Optimizations

### ISSUE THREAD

**Issue by NebelNidas** [Madis0/fabulously-optimized#40]
**Mod name**
Hopper Optimizations (+ required custom Lithium fork)

**Curseforge link**
N/A

**Modrinth link**
N/A

**Other link**
https://github.com/2No2Name/hopperOptimizations
Custom Lithium fork see at releases page

**What it does**
Hopper Optimizations is a fabric mod that reduces hopper, hopper minecart and comparator lag a lot without breaking any contraptions or odd vanilla behaviors. This branch of hopper optimizations requires installing a custom fork of Lithium.

**Why should it be in the modpack**
It drastically improves hopper performance on (internal) servers without any drawbacks.

**Why shouldn't it be in the modpack**
It is really stable and has no known incompatibilities; the only issue is that there's no CurseForge/Modrinth page. Which isn't really a bad thing, since pre-compiled jars are available on the GitHub releases page anyway.
Also, one could argue that requiring a custom Litium-fork would be a bad thing, which would usually be true. But in this case it's not, since HopperOptimizations is made by the lead-developer of Lithium anyway, so he knows what he does.

**Categories**

- [x] Performance optimization
- [ ] Graphics optimization
- [ ] New feature
- [ ] Optifine parity
- [ ] Fixes a bug/dependency
- [ ] Replaces an existing mod

**Additional details**
It is planned to merge this mod into Lithium some time in the future.

**Comment by Madis0** [comment]
Custom fork of Lithium is not allowed by CF rules though, because Lithium itself is on CF. Best bet is to wait for Lithium update.

**Comment by NebelNidas** [comment]
Hmm, but it's made by the same developer, and there are differences in the codebase (so it's not equal to the CurseForge version, which should be allowed?) 🤔

**Comment by Madis0** [comment]
Yeah, that's not really how this works. https://support.overwolf.com/en/support/solutions/articles/9000197913-non-curseforge-mods
