### ISSUE TITLE
Fast Furnace

### ISSUE THREAD

**Issue by NebelNidas** [Madis0/fabulously-optimized#41]
**Mod name**
Fast Furnace

**Curseforge link**
https://www.curseforge.com/minecraft/mc-mods/fast-furnace-for-fabric

**Modrinth link**
N/A

**Other link**
https://github.com/Tfarcenim/FabricFastFurnace

**What it does**
This mod does a few things relating to the vanilla furnace, blast furnace, and smoker so that they run faster during their update method, improving TPS.

**Why should it be in the modpack**
See above

**Why shouldn't it be in the modpack**
N/A

**Categories**

- [x] Performance optimization
- [ ] Graphics optimization
- [ ] New feature
- [ ] Optifine parity
- [ ] Fixes a bug/dependency
- [ ] Replaces an existing mod

**Additional details**
Fast Furnace wasn't updated for quite a few months, but recently a 1.16.5 version has been pushed out. Meanwhile, some parts of the mod have been integrated into Fabric API already, but not all (so it still gives a performance improvement):

![image](https://user-images.githubusercontent.com/48808497/114776579-ec3a2c00-9d72-11eb-9074-e64886196c87.png)
(https://www.curseforge.com/minecraft/mc-mods/fast-furnace-for-fabric?comment=20)

**Comment by Madis0** [comment]
I'm confused about what it does and where. Does it only work on singleplayer? Only on Fabric servers?

"Caching the recipe lookup" sounds like it could conflict with servers/maps that add and remove recipes on demand, like some old ViaVersion servers or new minigame maps.
Also concerned about having any perceptible benefit, maybe it's just better to merge it fully with Fabric API.

**Comment by NebelNidas** [comment]
![image](https://user-images.githubusercontent.com/48808497/114819988-99866180-9dbe-11eb-8549-fa6d8992e1a4.png)

So it doesn't help when playing on servers, but it speeds up the internal server when in Singleplayer.

**Comment by Madis0** [comment]
Okay, _maybe_ but I still hope it will be included in Fabric API or Minecraft itself.

**Comment by CodeF53** [comment]
I have experience with hosting servers with FastFurnace and FastBench #43. 

Both mods consistently cause issues relating to shift clicking items around, while providing little performance gain (and sometimes a loss).

**Comment by Madis0** [comment]
Thank you.
