### ISSUE TITLE
DimensionalThreading

### ISSUE THREAD

**Issue by NebelNidas** [Madis0/fabulously-optimized#42]
**Mod name**
DimensionalThreading

**Curseforge link**
N/A

**Modrinth link**
N/A

**Other link**
https://github.com/WearBlackAllDay/DimensionalThreading

**What it does**
This project is a free and open-source Minecraft mod which optimizes the processing of multiple Dimensions, by assigning them independent threads. It works on both the client and server, and does not require the mod to be installed on both sides.

**Why should it be in the modpack**
Improves (internal) server performance for users who have a few threads to spare (quad-core processor or better).

**Why shouldn't it be in the modpack**
Users with very few threads (low-end PCs with dual-core etc.) might have worse performance than without the mod. Also has no CurseForge/Modrinth page, but is nevertheless really stable.

**Categories**

- [x] Performance optimization
- [ ] Graphics optimization
- [ ] New feature
- [ ] Optifine parity
- [ ] Fixes a bug/dependency
- [ ] Replaces an existing mod

**Additional details**

**Comment by Madis0** [comment]
According to the readme, this seems to be opt-in? That's bad if so, because I cannot expect users to manually enable this. 

Also you mentioned worse performance for some users (which are actually the target audience for the modpack) and there has been some really bad bugs and crashes previously, so it seems concerning as an optimization mod overall.

**Comment by NebelNidas** [comment]
Seems you're right, opt-in is bad... But all the bugs and crashes have been resolved, currently it runs flawlessly (on my server it runs for 2 months now with 50 mods no issues). Perhaps this could also be added to the add-an-optional-link-to-the-modpack-page category?
