### ISSUE TITLE
FastBench

### ISSUE THREAD

**Issue by NebelNidas** [Madis0/fabulously-optimized#43]
**Mod name**
FastBench

**Curseforge link**
https://www.curseforge.com/minecraft/mc-mods/fastbench-for-fabric

**Modrinth link**
N/A

**Other link**
https://github.com/Tfarcenim/FabricFastBench

**What it does**
This mod does a couple things relating to the vanilla workbench so that it runs faster and causes less network traffic. Basically see #41.

**Why should it be in the modpack**
See above

**Why shouldn't it be in the modpack**
The latest CurseForge release is out of date and doesn't work that well. But when compiling from [this PR](https://github.com/Tfarcenim/FabricFastBench/pull/10), it works with 1.16.5 no issues.

**Categories**

- [x] Performance optimization
- [ ] Graphics optimization
- [ ] New feature
- [ ] Optifine parity
- [ ] Fixes a bug/dependency
- [ ] Replaces an existing mod

**Comment by Madis0** [comment]
CF version must be up to date, "less network traffic" sounds like modifying packets yet again and therefore risking anticheats.

**Comment by NebelNidas** [comment]
Nope, it reduces network traffic by simply caching the crafting recipes, not packets are being manipuated
