### ISSUE TITLE
Overworld Two

### ISSUE THREAD

**Issue by NebelNidas** [Madis0/fabulously-optimized#44]
**Mod name**
Overworld Two

**Curseforge link**
https://www.curseforge.com/minecraft/mc-mods/overworld-two

**Modrinth link**
N/A

**Other link**
https://github.com/Gegy/overworld-two

**What it does**
This mod implements an alternative world generator that replicates the style of vanilla overworld generation while bringing improvements to performance.

**Why should it be in the modpack**
Some basic results show that it reduces world gen times by up to 50% on servers, and even more with Lithium and Phosphor installed.

**Why shouldn't it be in the modpack**
Seeds are different for Overworld Two worlds and vanilla ones. On the other hand, this mod is optional to the user as it must be explicitly selected:
> To access Overworld Two generation, you must use the world type on the selection screen

**Categories**

- [x] Performance optimization
- [ ] Graphics optimization
- [ ] New feature
- [ ] Optifine parity
- [ ] Fixes a bug/dependency
- [ ] Replaces an existing mod

**Comment by Madis0** [comment]
Not compatible with vanilla seeds and having to explicitly select it makes the UX worse anyway.
