### ISSUE TITLE
Item Model Fix

### ISSUE THREAD

**Issue by NebelNidas** [Madis0/fabulously-optimized#47]
**Mod name**
Item Model Fix

**Curseforge link**
https://www.curseforge.com/minecraft/mc-mods/item-model-fix

**Modrinth link**
N/A

**Other link**
https://github.com/PepperCode1/Item-Model-Fix

**What it does**
Fixes the gaps in generated item models.

**Why should it be in the modpack**
It fixes those annoying transparent lines in handheld items, see the CurseForge page.

**Why shouldn't it be in the modpack**
N/A

**Categories**

- [ ] Performance optimization
- [x] Graphics optimization
- [ ] New feature
- [ ] Optifine parity
- [x] Fixes a bug/dependency
- [ ] Replaces an existing mod

**Comment by Madis0** [comment]
Think I thought of this at some point but please Mojang, fix it upstream 😄

**Comment by Madis0** [comment]
Added
