### ISSUE TITLE
Fade In Chunks

### ISSUE THREAD

**Issue by JDar2K** [Madis0/fabulously-optimized#49]
**Mod name**
Fade In Chunks

**Curseforge link**
https://www.curseforge.com/minecraft/mc-mods/fade-in-chunks#c24

**Modrinth link**
https://modrinth.com/mod/fade-in-chunks

**Other link**
https://github.com/Johni0702/fade-in-chunks

**What it does**
Adds a (Bedrock-style) fade-in animation to newly loaded chunks.

**Why should it be in the modpack**
Adds parity between Java Edition and Bedrock Edition

**Why shouldn't it be in the modpack**
Doesn't add much and requires fog to work correctly.

**Categories**

- [ ] Performance optimization
- [x] Graphics optimization
- [ ] New feature
- [ ] Optifine parity
- [ ] Fixes a bug/dependency
- [ ] Replaces an existing mod

**Additional details**
Maybe have this as an optional mod.

**Comment by Madis0** [comment]
I think the chunk loading should be subtle, not flashy - this looks very distracting, especially on shorter distances.

One could also compare that with [the current way](https://www.youtube.com/watch?v=FEdt1lQsJDo), video made by one of the pack's users.

**Comment by TheMadHau5** [comment]
IMHO this isn't flashy, and it replaces the chunks suddenly popping into existence with a much smoother fade.

**Comment by Rajbir98** [comment]
It also ave compaibility problems

**Comment by Rajbir98** [comment]
with sodium
