### ISSUE TITLE
Connected Block Textures

### ISSUE THREAD

**Issue by Madis0** [Madis0/fabulously-optimized#5]
**Mod name**
Connected Block Textures

**Curseforge link**
https://www.curseforge.com/minecraft/mc-mods/connected-block-textures

**Modrinth link**
N/A

**Other link**
https://github.com/Nuclearfarts/connected-block-textures

**What it does**
Connects textures in supported resource packs using Optifine format

**Why should it be in the modpack**
Optifine parity

**Why shouldn't it be in the modpack**
CF version incompatible with 1.17.x, mod dev seems to focus on Quilt now

**Categories**

- [ ] Performance optimization
- [x] Graphics optimization
- [ ] New feature
- [x] Optifine parity
- [ ] Fixes a bug/dependency

**Additional details**

Previous issue with 1.16.5: https://github.com/Nuclearfarts/connected-block-textures/issues/38

**Comment by MulverineX** [comment]
1.16 & 1.17 work with these builds https://github.com/HyperCubeMC/connected-block-textures/actions, even though they're not official I think you could probably get CF to review them. Nuclearfarts will not be releasing a working 1.16 build nor a 1.17 update until Quilt Loader releases & won't be doing Fabric Loader releases, so its probably worth going through the trouble.

**Comment by Madis0** [comment]
Yes, that is one way... But maybe the dev is willing to release their own version in CF/MR, if the original really will be delayed for months. I'll see when Indium gets released.
