### ISSUE TITLE
Water Render issues.

### ISSUE THREAD

**Issue by mscatloaf** [Madis0/fabulously-optimized#55]
When using this modpack I'm having issues with water rendering. The issues are shown in these pictures:
![2021-05-20_16 05 34](https://user-images.githubusercontent.com/80300628/119059706-b3026680-b985-11eb-912c-71f92dc3f723.png)
![2021-05-20_16 05 43](https://user-images.githubusercontent.com/80300628/119059710-b39afd00-b985-11eb-8c49-33de3db7b968.png)
![2021-05-20_16 05 52](https://user-images.githubusercontent.com/80300628/119059711-b39afd00-b985-11eb-99ef-3df9d3f9ef23.png)
![2021-05-20_16 06 00](https://user-images.githubusercontent.com/80300628/119059712-b4339380-b985-11eb-8388-8a5f05ded350.png)
![2021-05-20_16 06 17](https://user-images.githubusercontent.com/80300628/119059714-b4339380-b985-11eb-919f-e3d702503ab9.png)

My cpu is Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz, 2208 Mhz, 6 Core(s), 12 Logical Processor(s)

I have 16 gb of sodimm ram at 2400 mhz

And my GPU is NVIDIA GTX 1060 mobile (using latest drivers)

I am using the curseforge version of the mod if that helps

**Comment by TheMadHau5** [comment]
???
