### ISSUE TITLE
Cull Particles Fabric

### ISSUE THREAD

**Issue by Madis0** [Madis0/fabulously-optimized#58]
**Mod name**
Cull Particles Fabric

**Curseforge link**
https://www.curseforge.com/minecraft/mc-mods/cull-particles-fabric

**Modrinth link**

**Other link**

**What it does**
Stops rendering of particles you can't see

**Why should it be in the modpack**
Higher FPS

**Why shouldn't it be in the modpack**
Some people claim it doesn't work at all at the moment, needs testing

**Categories**

- [x] Performance optimization
- [ ] Graphics optimization
- [ ] New feature
- [ ] Optifine parity
- [ ] Fixes a bug/dependency
- [ ] Replaces an existing mod

**Additional details**

**Comment by NebelNidas** [comment]
![image](https://user-images.githubusercontent.com/48808497/123136984-d07a9280-d453-11eb-94a8-d199b1317bb7.png)

**Comment by Madis0** [comment]
Thanks.
