### ISSUE TITLE
Advancements Enlarger

### ISSUE THREAD

**Issue by itsmeboy0** [Madis0/fabulously-optimized#60]
**Mod name**
Advancements Enlarger

**Curseforge link**
https://www.curseforge.com/minecraft/mc-mods/advancements-enlarger

**Modrinth link**

**Other link**
https://github.com/shedaniel/advancements-enlarger

**What it does**
Makes the advancement menu take up most of the available space.

**Why should it be in the modpack**
A bigger view of the advancement menu.

**Why shouldn't it be in the modpack**
Cannot set the size of the window yet (https://github.com/shedaniel/advancements-enlarger/issues/2).

**Categories**

- [ ] Performance optimization
- [x] Graphics optimization
- [ ] New feature
- [ ] Optifine parity
- [ ] Fixes a bug/dependency
- [ ] Replaces an existing mod

**Additional details**

**Comment by Madis0** [comment]
Indeed, I do think the advancement screen is way too small to be useful. However, it may be worth considering this mod instead, which also adds a "to-do list" for each advancement. https://www.curseforge.com/minecraft/mc-mods/advancementinfo

**Comment by Madis0** [comment]
#68 was added instead.
