### ISSUE TITLE
Audio Output

### ISSUE THREAD

**Issue by itsmeboy0** [Madis0/fabulously-optimized#61]
**Mod name**
Audio Output

**Curseforge link**
https://www.curseforge.com/minecraft/mc-mods/audio-output

**Modrinth link**

**Other link**

**What it does**
Change the audio output device from Minecraft itself

**Why should it be in the modpack**
You don't have to restart Minecraft everytime you change your audio output device

**Why shouldn't it be in the modpack**
N/A

**Categories**

- [ ] Performance optimization
- [ ] Graphics optimization
- [x] New feature
- [ ] Optifine parity
- [ ] Fixes a bug/dependency
- [ ] Replaces an existing mod

**Additional details**
Somehow not open source. So far everything in this modpack is OSS. Does not stop it from being useful though.

**Comment by Madis0** [comment]
One of the comments says
> I used to fix sound problems with F3+t but no more

So if this does indeed work the same, then I don't think the mod is necessary. I would really like to avoid adding mods that fix some very specific problems, for that I encourage simply adding custom mods by every user of the pack or reporting bugs to Mojang's bugtracker.

**Comment by itsmeboy0** [comment]
> One of the comments says
> 
> > I used to fix sound problems with F3+t but no more
> 
Does work, but my use case is I would want to switch to different audio devices back and forth easily. Sometimes, I would have my computer output mainly in my speakers while Minecraft audio playing on my headphones. Don't know if this is a very specific problem.

**Comment by Madis0** [comment]
Do I understand it correctly: this _can_ still be done using system settings, Minecraft just needs F3+T to be pressed for it to take effect?

**Comment by itsmeboy0** [comment]
> Do I understand it correctly: this _can_ still be done using system settings, Minecraft just needs F3+T to be pressed for it to take effect?

No you cant, that is why this plugin exists. According to the [wiki](https://minecraft.fandom.com/wiki/Controls):

> Pressing `T` while holding `F3` reloads all textures, sounds and web-loaded client resources, which is useful for resource pack authors.

It reloads everything, including sounds, so it fixes any sound problems if you have any. However, it does not "switch" to a specific audio output. It does switch on to the new audio output you have connected to your computer (which is not switching to a specific output).

**Comment by wafflecoffee** [comment]
By the way, this would no longer be needed in 1.18 snapshots if a snapshot pack is to be created, as the mod's functionality has been implemented into vanilla

**Comment by Madis0** [comment]
Yup, but I am planning to include it exactly for the sake of 1.18 parity :grin:
