### ISSUE TITLE
Too Many Binds

### ISSUE THREAD

**Issue by timocarnill** [Madis0/fabulously-optimized#611]
### CurseForge link

https://www.curseforge.com/minecraft/mc-mods/too-many-binds

### CurseForge Mod Distribution

Allowed

### Modrinth link

https://modrinth.com/mod/too-many-binds

### Mod file size

31.49 KB

### License

(any other license)

### What it does

It has two keybinds. One pops up a menu that allows you to execute any keybind from the controls menu, even if unbinded.
The other "favorites" one of those binds so it's easier to get next time. 

### Why should it be in the modpack

I think it's a great quality-of-life mod, especially if you have loads of other keybinds, or are playing with a controller (having fewer buttons)

### Why shouldn't it be in the modpack

Some people could maybe consider it slightly un-vanilla. But you don't have to use it if you don't want to :shrug: 
Also it doesn't work for keybinds that aren't configured in the vanilla keybind menu (e.g. MiniHud, tweakeroo, litematica etc.)

**Comment by Madis0** [comment]
Well, I use the mod personally and I like it, but why do you think it fits to FO? FO doesn't have that many keybinds...

**Comment by Madis0** [comment]
Lack of response, so rejected.

**Comment by timocarnill** [comment]
I think seeing as the mod that allows you to use a controller (can't remember it's name) is already in this, they'd go well with each other.

**Comment by Madis0** [comment]
You're referring to MidnightControls and it does have a "Unbound Keybind Ring" already. 
![2023-04-04_20 57 47](https://user-images.githubusercontent.com/8611110/229878256-395e170b-d297-44f0-94ef-44c4a7b8280e.png)

**Comment by hschwar** [comment]
Could this mod be reconsidered as Controlify does not have the above feature?

**Comment by Madis0** [comment]
> Could this mod be reconsidered as Controlify does not have the above feature?
> 
> There is a pull request for a 1.20 version in its GitHub page

[It is being worked on though.](https://discord.com/channels/780023008668287017/1003235128283254874/1129085309817192518) [(via)](https://discord.gg/8DNCP3aXgK)
