### ISSUE TITLE
Better Mount HUD

### ISSUE THREAD

**Issue by Madis0** [Madis0/fabulously-optimized#64]
**Mod name**
Better Mount Hud

**Curseforge link**
https://www.curseforge.com/minecraft/mc-mods/better-mount-hud

**Modrinth link**

**Other link**

**What it does**
Displays your food and entity's health at the same time, jump bar is only shown when actually jumping

**Why should it be in the modpack**
A good UX tweak

**Why shouldn't it be in the modpack**
Maybe someone prefers vanilla behaviour?

**Categories**

- [ ] Performance optimization
- [ ] Graphics optimization
- [x] New feature
- [x] ~~Optifine~~ Bedrock parity
- [ ] Fixes a bug/dependency
- [ ] Replaces an existing mod

**Additional details**

https://gitlab.com/Lortseam/better-mount-hud/-/issues/2

**Comment by TheMadHau5** [comment]
What about the breathing bubbles?

**Comment by Madis0** [comment]
@TheMadHau5 If you're underwater, the horse will dismount anyway. Probably the same with pigs and striders.

**Comment by TheMadHau5** [comment]
Well yes but skeleton horses.

**Comment by Madis0** [comment]
Good point. I'll test this at some point and see how it works in that case.

**Comment by Madis0** [comment]
The mod got an update and it fixed the issue, so I'll likely include this in 2.0 stable. Fun fact: this matches the behaviour of Bedrock Edition :)

**Comment by TheMadHau5** [comment]
Nice!
