### ISSUE TITLE
IrisShaders for OF shader support

### ISSUE THREAD

**Issue by Fauli1221** [Madis0/fabulously-optimized#65]
**Mod name**
IrisShaders

**Curseforge link**
not yet available

**Modrinth link**
not yet available

**Other link**
https://github.com/IrisShaders/Iris

**What it does**
A new shaders mod for Minecraft intended to be compatible with existing ShadersMod/Optifine shaders

**Why should it be in the modpack**
propper shader support
parity with Optifine

**Why shouldn't it be in the modpack**
the turn on and of shader button is broken to toggle it you need to press the hotkey
needs a custom sodium version or the builtin one
incompatible with canvas

**Categories**

- [ ] Performance optimization
- [x] Graphics optimization
- [ ] New feature
- [x] Optifine parity
- [ ] Fixes a bug/dependency
- [x] Replaces an existing mod

**Additional details**
there is work being done to make the official version of sodium compatible

**Comment by Madis0** [comment]
Thanks for the suggestion! The mod is already being tracked on #12
