### ISSUE TITLE
Black world

### ISSUE THREAD

**Issue by Matzzxd** [Madis0/fabulously-optimized#69]
Just joined a server, o created a world in singleplayer, the world is completely black, except, grass, water, the sky and mobs

Installed the 1.17 beta version with the mods (mods for multiMC) for standard Minecraft launcher - Tlauncher

I just wanted for my pc to handle the actual minecraft faster, with faster fps

https://imgur.com/a/b2nWTnO

 - Modpack version: Fabulously Optimized 2.0.0b2 beta for 1.17
 - Launcher: Tlauncher

What to do???? Can I solve this problem by deleting some mod?

**Comment by Madis0** [comment]
This is probably caused by Canvas, try removing that. 

I only use Canvas on the beta versions of the pack while Sodium is not available, so hopefully soon you can use the pack as-is with better FPS :) Or just use 1.16.5 version in the meanwhile.

**Comment by Matzzxd** [comment]
Yeah, thanks a lot, it helped, and fixed the problem, I can see clearly now! :)
https://imgur.com/a/mUZmBWb
