### ISSUE TITLE
Fat Experience Orbs

### ISSUE THREAD

**Issue by Rajbir98** [Madis0/fabulously-optimized#71]
**Mod name**

[Fabric] Fat Experience Orbs

**Curseforge link**
https://www.curseforge.com/minecraft/mc-mods/fat-experience-orbs

**Modrinth link**
N/A

**Other link**
N/A

**What it does**
This mod makes it so that nearby experience orbs merge together, when installed on the client this mod allows experience orbs to merge in single player. When installed on a dedicated server no client is required to have the mod.

**Why should it be in the modpack**
No lag In XP Farms

**Why shouldn't it be in the modpack**
Mods will go without support of any kind, simple updates to new versions is still a possibility.

**Categories**

- [x] Performance optimization
- [ ] Graphics optimization
- [ ] New feature
- [ ] Optifine parity
- [ ] Fixes a bug/dependency
- [ ] Replaces an existing mod

**Additional details**
N/A

**Comment by Madis0** [comment]
Current thoughts:
* changes vanilla behavior a bit too much, defying expectations
* only in singleplayer is a shame 
* I wonder how often/significantly it actually helps with FPS

**Comment by CodeF53** [comment]
As someone who uses a rough equivalant to this feature: [Carpet's combineXPOrbs](https://github.com/gnembon/fabric-carpet/wiki/Current-Available-Settings#combinexporbs)

1. When designing/using overkill XP farms, this 100% helps with lag.
2. Users that need this feature will likely have carpet installed themselves, so don't need a mod for it.

**Comment by Rajbir98** [comment]
nice thx for a new alternative of this mod

**Comment by Rajbir98** [comment]
may i add carpet to issues

**Comment by Rajbir98** [comment]
as mod request i think people will like this and i will close this
