### ISSUE TITLE
Chime

### ISSUE THREAD

**Issue by CodeF53** [Madis0/fabulously-optimized#77]
# Chime
## [Curseforge](https://www.curseforge.com/minecraft/mc-mods/chime-fabric) &nbsp; [Modrinth](https://github.com/emilyalexandra/chime) &nbsp; [Github](https://modrinth.com/mod/chime)  

**What it does**
Adds a predicate system for more dynamic and interesting item model variation

**Why should it be in the modpack**
Alternative for Optifine CIT. 

**Why shouldn't it be in the modpack**
Not many packs support it. <br> (could be solved by [MCPPPP](https://github.com/supsm/MCPPPP)) 

**Categories**

- [ ] Performance optimization
- [ ] Graphics optimization
- [x] New feature
- [x] Optifine parity
- [ ] Fixes a bug/dependency
- [ ] Replaces an existing mod

**Additional details** by Madis0

https://github.com/LambdAurora/MCPatcherPatcher/issues/18#issuecomment-839152883

**Comment by Madis0** [comment]
Is there a way to convert them automatically like #73?

**Comment by CodeF53** [comment]
Yes, but the program is currently work in progress.
https://github.com/supsm/MCPPPP
MCPatcherPatcher++

**Comment by Madis0** [comment]
@CodeF53 Yeah, that's an external program, but what about Fabric mods, are there any that would convert on runtime?

**Comment by CodeF53** [comment]
No

**Comment by Madis0** [comment]
In that case, sorry, this will not be considered for now. People who know how to use conversion programs also know how to install custom mods 😛

**Comment by Madis0** [comment]
Feasible again via #106
