### ISSUE TITLE
Carpet

### ISSUE THREAD

**Issue by Rajbir98** [Madis0/fabulously-optimized#79]
**Mod name**
Fabric Carpet

**Curseforge link**
https://www.curseforge.com/minecraft/mc-mods/carpet

**Modrinth link**

**Other link**
https://github.com/gnembon/fabric-carpet

**What it does**
Carpet is a mod that allows to take full control over your vanilla game.
And can fix lag very much in multiplayer and single player 

**Why should it be in the modpack**Can be complicated for everyone

**Why shouldn't it be in the modpack**
Can have incompaibilities with other mods

**Categories**

- [x] Performance optimization
- [ ] Graphics optimization
- [x] New feature
- [ ] Optifine parity
- [x] Fixes a bug/dependency
- [ ] Replaces an existing mod

**Additional details**
What is carpet mod?

Carpet Mod is a mod for vanilla Minecraft that allows you to take full control of what matters from a technical perspective of the game.

Test your farms over several hours in only a few minutes using /tick warp
...and then see a detailed breakdown of the items they produce using hopperCounters
See the server mobcap, TPS, etc. update live with /log
Let pistons push block entities (ie. chests) with movableBlockEntities
Fix many things

See the mod showcase on youtube for an explanation of every setting and command
Is it client only?

No dummy, that's why further down the page there is a heading called 'Server administration and carpet.conf file'
Why it is called 'carpet mod' and how it affects carpets?

Cos gnembon initially made it so that you could place down carpets and they would tell you stuff.
How can I learn to use carpet mod?

https://www.youtube.com/watch?v=Lt-ooRGpLz4
How to control fake players for simulating real behaviours

https://www.youtube.com/watch?v=Lt-ooRGpLz4&t=1685s
Carpet configuration and carpet.conf file
Scarpet notes

Learning Scarpet is not trivial, but doesn't have to be difficult. Here are a few pages that you can use to learn how to use it in carpet:

**Comment by Rajbir98** [comment]
I got this mod by a comment in my other issue #71

**Comment by Rajbir98** [comment]
carpet can fulfill requirement of many mods

**Comment by CodeF53** [comment]
I feel like this will 100% be considered "out of scope"

I am considering making a branch of this modpack that is for technical minecrafters.

**Comment by Rajbir98** [comment]
ok

**Comment by Rajbir98** [comment]
but it can be useful for me

**Comment by Madis0** [comment]
That's right, that kind of mod needs learning and goes further away from vanilla, so it wouldn't suit my target audience which is light or first-time modders that just want to make the vanilla game work a bit better.
