### ISSUE TITLE
Enable End Gateway Culling

### ISSUE THREAD

**Issue by cochcoder** [Madis0/fabulously-optimized#794]
### What config to change

In the newest version of More Culling, version 0.21.0, the option of End Gateway culling was added but is not enabled by default like Beacon Beam culling is. 

### Why should it be changed

This increases FPS while you're near a End Gateway due to culling. 

### Additional details

In my testing, this increases FPS by ~10 FPS.

**Comment by cochcoder** [comment]
Issue is now fixed in the latest version

**Comment by Madis0** [comment]
Done in FO 5.6.5
