### ISSUE TITLE
User overrides for auto-update pack

### ISSUE THREAD

**Issue by Remty5** [Madis0/fabulously-optimized#81]
I'm using the auto updating pack but I havent seen a way to override mods if you want to manually update/replace them.
Is there a way to do this with the modpack?

I'm using MultiMC running under Linux and made [pre-launch and post-launch scripts](https://gist.github.com/Remty5/1b8a8d7c842dda56dacebf6db8c10961) to deal with overrides.
I don't know if you will be able to do something about overrides, but at least I wanted to share my script if others are in a similar situation.

**Comment by Madis0** [comment]
Unfortunately no, I don't know any way to do this but you could suggest it to the tool I'm using, packwiz.

**Comment by Remty5** [comment]
I'll let you decide if you want to close this issue, you could maybe link it in the wiki somewhere.

**Comment by Madis0** [comment]
Suggested to packwiz, as it should be done on their end.
