### ISSUE TITLE
Fast Furnace Mod and Krypton Mod

### ISSUE THREAD

**Issue by TechPro424** [Madis0/fabulously-optimized#84]
Fast Furnace: https://www.curseforge.com/minecraft/mc-mods/fast-furnace-for-fabric

This is similar to fast chests, but for furnaces.

Krypton: https://modrinth.com/mod/krypton

This one optimizes the Minecraft networking stack, using code from the Velocity and Tunity projects.

**Comment by Madis0** [comment]
Duplicates of #41 and #9.

Please search before creating, do one request per issue and fill the missing fields.
