### ISSUE TITLE
auto updating pack for Vanilla Launcher

### ISSUE THREAD

**Issue by TechPro424** [Madis0/fabulously-optimized#88]
Is it possible to add an auto updating pack for Vanilla Launcher?

**Comment by Madis0** [comment]
This is planned as soon as packwiz adds support for it.

**Comment by Rajbir98** [comment]
it will be very good if this happens

**Comment by TechPro424** [comment]
Ok, so according to the above comment, support for this is planned sooner or later.
That's nice! Therefore, I'm closing this issue.
