### ISSUE TITLE
Krypton

### ISSUE THREAD

**Issue by Madis0** [Madis0/fabulously-optimized#9]
**Mod name**
Krypton

**Curseforge link**
https://www.curseforge.com/minecraft/mc-mods/krypton

**Modrinth link**
N/A

**Other link**
https://github.com/astei/krypton

**What it does**
Improves "networking stack", so possibly world loading and multiplayer

**Why should it be in the modpack**
Performance optimizations

**Why shouldn't it be in the modpack**
Needs more testing to know it works well in every situation

**Categories**

- [x] Performance optimization
- [ ] Graphics optimization
- [ ] New feature
- [ ] Optifine parity
- [ ] Fixes a bug/dependency

**Additional details**

**Comment by NebelNidas** [comment]
Some stuff is Linux-only, but many other optimizations still work with Windows/macOS. I use it with AntiGhost and haven't noticed any issues, and the ViaVersion conflict has been resolved: https://github.com/ViaVersion/ViaFabric/issues/89
I don't see why servers should disallow the mod (even if they do, can they even notice that you have the mod?).

**Comment by Madis0** [comment]
> I don't see why servers should disallow the mod (even if they do, can they even notice that you have the mod?).

From what I understand, it changes the way some packets work, so it may get people banned through some anti-cheat plugins.

**Comment by NebelNidas** [comment]
From the CurseForge page:
> Krypton is a Minecraft mod designed for the Fabric mod loader that implements a suite of optimizations focused on the Minecraft networking stack. It works on both clients and servers, although it is the most useful on servers.

But I guess you are right, it's not wort the risk of perhaps getting banned. Nevertheless, you could add a notice on the modpack site that Krypton can be used at one's own risk? 🤷‍♂️

**Comment by fredster33** [comment]
On anecdotal evidence: I've tested this out extensively and it doesn't seem to increase performance.

**Comment by NebelNidas** [comment]
> it doesn't seem to increase performance

That's because Krypton isn't supposed to boost your FPS, but to reduce Internet traffic. If you have a good Internet connection, you won't notice much/any improvement, but for the many people out there (or server owners) who get regularly bottlenecked by theirs, it works true wonders 😉

**Comment by fredster33** [comment]
Ah, got it. Yeah, didn't seem to change anything Internet-wise, I have fairly nice Internet fortunately.

**Comment by nsde** [comment]
I'm using Linux :+1: 
I know it's rejected but still, maybe not a very good argument

**Comment by Madis0** [comment]
Well, I and many others are using Linux as well.
But the main reasons why this is rejected are:

- it may be disallowed on major servers
- nobody has convinced me this _actually helps something_ on client-side
- if it does help, what are the preconditions for it?

**Comment by Kichura** [comment]
Update about mod *(hopefully the last one)*: The mod itself on client is considered useless to have as the memory leak fix it provides is so hard to notice that you would need to rejoin servers atleast more than a thousand times just to notice any impact and that the networking speed isn't a big deal with it whatsoever as client never sends large or many packets *(only server does this)* - hence if you wish to fix any networking issues, just use raknetify or lithium if you are willing to optimize anything like that.
