### ISSUE TITLE
Custom Entity Models

### ISSUE THREAD

**Issue by Madis0** [Madis0/fabulously-optimized#92]
### Mod name

Custom Entity Models (CEM)

### Curseforge link

https://www.curseforge.com/minecraft/mc-mods/custom-entity-models-cem

### What it does

Adds Optifine-compatible entity model support

### Why should it be in the modpack

Optifine parity

### Why shouldn't it be in the modpack

Alpha, rendering API, limited mobs

### Categories

Graphics optimization, Works like Optifine/Bedrock Edition/Forge/etc

**Comment by CodeF53** [comment]
The release builds of the mod have 100% parity for the entities they support, no reason for this not to be included.

**Comment by Madis0** [comment]
We still need Sodium and Indium, but true.

**Comment by CodeF53** [comment]
> We still need Sodium and Indium, but true.

I am checking if those are compatible with this tonight. 
(also working on a 1.16 backport of the new mobs)

**Comment by Madis0** [comment]
Welp, now I read this part:
>  For resource packs intended to be used with Optifine, renaming "assets/minecraft/optifine/cem" to "assets/dorianpb/cem" should work fine.

I cannot expect my users to do that for every resource pack, so I cannot include this yet 😞

**Comment by CodeF53** [comment]
IIRC you dont have to do that anymore.

**Comment by Madis0** [comment]
I tested some random resource packs I found when searching for "entity models"

- https://www.curseforge.com/minecraft/texture-packs/super-mario-craft
- https://www.curseforge.com/minecraft/texture-packs/mickey-joes-relatively-improved-default
- https://www.curseforge.com/minecraft/texture-packs/enhanced-mobs-resource-pack-optifine-required

and I can't really say that they have "100% parity for the entities they support", only a few mobs looked correct (Mario Craft's creeper and chicken). However, it may be the case like Iris where there are few resource packs that are supported well, so I'll include this mod in beta 4 for people to test regardless.
