### ISSUE TITLE
Cull leaves resource pack reduces FPS when in areas with a lot of leaves

### ISSUE THREAD

**Issue by tpdcl** [Madis0/fabulously-optimized#93]
### Describe the bug

When using the cullleaves/smartleaves resource pack with the mod off (default config), going somewhere where there are a lot of leaves reduces FPS drastically, from 90-120 to 30-40

### Expected behavior

No performance drop

### Observed/actual behavior

Performance drop

### Steps To Reproduce

1. Install the modpack
2. Open MC
3. Go in a forest/tree farm/etc.
4. Observe the lag

### Modpack version

2.1.0a2

### Launcher

Other (please write below)

### Install method

Fresh install/new profile

### Additional context

I am using TLauncher

**Comment by Madis0** [comment]
I recommend enabling Cull Leaves as well and seeing if that will fix the FPS.

**Comment by tpdcl** [comment]
It does. Shouldn't this be the default to prevent confusion if someone installs the pack and notices their performance dropping instead of increasing?

**Comment by Madis0** [comment]
Well, I didn't enable Cull Leaves by default because it changes the visuals a bit. However, now that I have defaulted to fast graphics, I might as well enable that too, will do in the next version.

**Comment by Madis0** [comment]
Okay, now I realized the resource pack is enabled by default, I thought it was opt-in (as it used to be on 1.16.x at least, or so I recall) 😁 

Anyway, fixed on 2.1.0-alpha.3
