### ISSUE TITLE
Limited FPS with fullscreen

### ISSUE THREAD

**Issue by Saumy-coder** [Madis0/fabulously-optimized#94]
### Describe the bug

This is a great modpack and gives me a tons of fps boost. Like with optifine I get 60-100 fps but with this I get 100-250 fps. But when I fullscreen my game limits the fps to 58-61 neither go up nor go down like just stuck there at 60. Look on the mods cause that never happens

### Expected behavior

Normal fps with fullscreen

### Observed/actual behavior

FPS only stuck at 60 at fullscreen

### Steps To Reproduce

I have no idea for this

### Modpack version

1.9.1 - MC 1.16.5

### Launcher

Minecraft Launcher (vanilla)

### Install method

Upgraded an existing profile (please write below, what version to what version)

### Additional context

I use the mods from the modpack on Fabric loader

**Comment by Madis0** [comment]
Try adding #78 to your profile and see if it fixes your issue.

**Comment by Madis0** [comment]
Probably fixed with 2.1.0.
