### ISSUE TITLE
Visual Glitches 

### ISSUE THREAD

**Issue by Gavins38** [Madis0/fabulously-optimized#96]
### Describe the bug

Theres a bug/glitch where theres just visual glitches everywhere
SEE screenshots
![2021-07-18_08 13 52](https://user-images.githubusercontent.com/67829574/126066806-9f7daf98-994e-4f89-81c2-0d6628dec35c.png)
![2021-07-18_08 14 00](https://user-images.githubusercontent.com/67829574/126066807-772216b6-7de7-4682-aab7-b83ecb162ca4.png)
![2021-07-18_08 16 04](https://user-images.githubusercontent.com/67829574/126066809-e940dc34-686e-463f-9727-d47526440439.png)

### Expected behavior

to work

### Observed/actual behavior

Visual glitches

### Steps To Reproduce

Play minecraft see visual bug

### Modpack version

2.1.0-beta 1.17.1

### Launcher

Minecraft Launcher (vanilla)

### Install method

Fresh install/new profile

### Additional context

playing 1.16 with fabulously optimized works perfectly fine, i think theres either a conflicting mod in the 2.1.0 beta 1.17.1 modpack or a mod is outofdate and isnt working.

**Comment by Gavins38** [comment]
I removed all the mods and just ran sodium with sodium extras and i think sodium is having issues

**Comment by Madis0** [comment]
I see you already reported it, that's great. https://github.com/CaffeineMC/sodium-fabric/issues/774

**Comment by technicaldiff** [comment]
yeah a lot of older gpus are currently having issues with sodium 1.17.1+0.3.0
might want tot wait before proceeding with install

**Comment by Gavins38** [comment]
like wait for sodium to update?

**Comment by Madis0** [comment]
Well, as Jelly said on her Discord, this appears on some machines and works perfectly on others, so it is just a matter of trying and seeing. 

I'll continue updating to newest versions of Sodium+Iris whenever they come available and I'll keep the FO version marked as beta as long as there still are major issues.

**Comment by Gavins38** [comment]
Yeah my bug report got added to a list of same bug reports.

**Comment by Madis0** [comment]
Jelly provided a test build for those affected: https://discord.com/channels/602796788608401408/651120262129123330/866918012896804865

**Comment by Gavins38** [comment]
> Jelly provided a test build for those affected: https://discord.com/channels/602796788608401408/651120262129123330/866918012896804865

Yeah unfortunately it isnt working either lots of people are still saying that the dev builds didnt work either.

**Comment by Rajbir98** [comment]
> 
> 
> Jelly provided a test build for those affected: https://discord.com/channels/602796788608401408/651120262129123330/866918012896804865

This Discord Link Is not workin for me its showing failed to load messges my internet connection is fine

**Comment by Madis0** [comment]
@Rajbir98 It's an old build.

Go to https://jellysquid.me/discord and download the latest jar from #sodium-dev
