### ISSUE TITLE
Canvas Renderer not removed in 2.1.0-beta.1

### ISSUE THREAD

**Issue by nchristopher** [Madis0/fabulously-optimized#97]
### Describe the bug

In the changelog for `2.1.0-beta.1`, Canvas was supposedly removed. However, it's still present in the Packwiz config (`Packwiz/index.toml`).

Since Canvas conflicts with Sodium, this prevents the pack from starting up.

I'm using the auto-updating MultiMC pack, I'm not sure if this issue is present in other versions.

### Expected behavior

Canvas is removed as is conflicts with Sodium; the pack works normally.

### Observed/actual behavior

Fabric will display an error as Canvas conflicts with Sodium. This prevents the pack from starting.

### Steps To Reproduce

1) Install the auto-updating MultiMC pack.
2) Launch the pack.
3) Fabric will display an error as Canvas conflicts with Sodium.

### Modpack version

2.1.0-beta.1

### Launcher

MultiMC

### Install method

Fresh install/new profile

**Comment by Madis0** [comment]
Sorry about that. Fixed now, just relaunch the profile.
