### ISSUE TITLE
No shader file

### ISSUE THREAD

**Issue by Tajkobi09** [Madis0/fabulously-optimized#98]
### Describe the bug

I understand this is a 'shader' issue, however, my shaders work with everything else. So, when I go to the video setting there is no shader file, so I added my own and still no luck. 

### Expected behavior

A shader file in video settings

### Observed/actual behavior

No shader file even when manualy added

### Steps To Reproduce

restart mod
enter settings
no shader file

### Modpack version

Fabulously Optimized-2.1.0-beta.1.zip

### Launcher

Curseforge Launcher

### Install method

Fresh install/new profile

**Comment by Madis0** [comment]
2.1.0-beta.1 doesn't have shaders yet, still waiting for Iris to update to 1.17.1. Use 2.0.0b4 for now.

**Comment by Tajkobi09** [comment]
Okay all good thank you!
